
# This file is automatically generated, you probably don't want to edit this

mCOROptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mCOROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            selgroup = NULL,
            hyp = "corr",
            method = "pearson",
            adjust = "none",
            tables = TRUE,
            pval = TRUE,
            flag = FALSE,
            n = FALSE,
            ci = FALSE,
            ciWidth = 95,
            plots = FALSE,
            signif = "all",
            plotMetU = "ellipse",
            plotMetL = "ellipse",
            plotOrder = "original",
            hclust = FALSE,
            numClust = 2,
            clustMet = "ward.D2",
            clPos = "b",
            clustCol = FALSE,
            clustMan = "",
            clustMat = FALSE,
            glasso = FALSE,
            glassoTable = FALSE,
            glassoPlot = TRUE,
            glassoType = "ebic",
            glassoGamma = 0.5,
            glassoRho = 0.1,
            glassoHub = FALSE,
            glassoPlotScale = TRUE,
            glassoLabels = TRUE, ...) {

            super$initialize(
                package="jYS",
                name="mCOR",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..selgroup <- jmvcore::OptionLevel$new(
                "selgroup",
                selgroup,
                variable="(group)")
            private$..hyp <- jmvcore::OptionList$new(
                "hyp",
                hyp,
                options=list(
                    "corr",
                    "pos",
                    "neg"),
                default="corr")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson")
            private$..adjust <- jmvcore::OptionList$new(
                "adjust",
                adjust,
                options=list(
                    "none",
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "BH",
                    "BY"),
                default="none")
            private$..tables <- jmvcore::OptionBool$new(
                "tables",
                tables,
                default=TRUE)
            private$..pval <- jmvcore::OptionBool$new(
                "pval",
                pval,
                default=TRUE)
            private$..flag <- jmvcore::OptionBool$new(
                "flag",
                flag,
                default=FALSE)
            private$..n <- jmvcore::OptionBool$new(
                "n",
                n,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..signif <- jmvcore::OptionList$new(
                "signif",
                signif,
                options=list(
                    "all",
                    "0.1",
                    "0.05",
                    "0.01",
                    "0.001"),
                default="all")
            private$..plotMetU <- jmvcore::OptionList$new(
                "plotMetU",
                plotMetU,
                options=list(
                    "empty",
                    "circle",
                    "square",
                    "ellipse",
                    "number",
                    "shade",
                    "color",
                    "pie"),
                default="ellipse")
            private$..plotMetL <- jmvcore::OptionList$new(
                "plotMetL",
                plotMetL,
                options=list(
                    "empty",
                    "circle",
                    "square",
                    "ellipse",
                    "number",
                    "shade",
                    "color",
                    "pie"),
                default="ellipse")
            private$..plotOrder <- jmvcore::OptionList$new(
                "plotOrder",
                plotOrder,
                options=list(
                    "original",
                    "alphabet",
                    "AOE",
                    "FPC"),
                default="original")
            private$..hclust <- jmvcore::OptionBool$new(
                "hclust",
                hclust,
                default=FALSE)
            private$..numClust <- jmvcore::OptionNumber$new(
                "numClust",
                numClust,
                min=2,
                default=2)
            private$..clustMet <- jmvcore::OptionList$new(
                "clustMet",
                clustMet,
                options=list(
                    "ward.D",
                    "ward.D2",
                    "single",
                    "complete",
                    "average",
                    "mcquitty",
                    "median",
                    "centroid"),
                default="ward.D2")
            private$..clPos <- jmvcore::OptionList$new(
                "clPos",
                clPos,
                options=list(
                    "n",
                    "r",
                    "b"),
                default="b")
            private$..clustCol <- jmvcore::OptionBool$new(
                "clustCol",
                clustCol,
                default=FALSE)
            private$..clustMan <- jmvcore::OptionString$new(
                "clustMan",
                clustMan,
                default="")
            private$..clustMat <- jmvcore::OptionBool$new(
                "clustMat",
                clustMat,
                default=FALSE)
            private$..glasso <- jmvcore::OptionBool$new(
                "glasso",
                glasso,
                default=FALSE)
            private$..glassoTable <- jmvcore::OptionBool$new(
                "glassoTable",
                glassoTable,
                default=FALSE)
            private$..glassoPlot <- jmvcore::OptionBool$new(
                "glassoPlot",
                glassoPlot,
                default=TRUE)
            private$..glassoType <- jmvcore::OptionList$new(
                "glassoType",
                glassoType,
                options=list(
                    "ebic",
                    "manual"),
                default="ebic")
            private$..glassoGamma <- jmvcore::OptionNumber$new(
                "glassoGamma",
                glassoGamma,
                min=0,
                max=1,
                default=0.5)
            private$..glassoRho <- jmvcore::OptionNumber$new(
                "glassoRho",
                glassoRho,
                min=0,
                max=10,
                default=0.1)
            private$..glassoHub <- jmvcore::OptionBool$new(
                "glassoHub",
                glassoHub,
                default=FALSE)
            private$..glassoPlotScale <- jmvcore::OptionBool$new(
                "glassoPlotScale",
                glassoPlotScale,
                default=TRUE)
            private$..glassoLabels <- jmvcore::OptionBool$new(
                "glassoLabels",
                glassoLabels,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..selgroup)
            self$.addOption(private$..hyp)
            self$.addOption(private$..method)
            self$.addOption(private$..adjust)
            self$.addOption(private$..tables)
            self$.addOption(private$..pval)
            self$.addOption(private$..flag)
            self$.addOption(private$..n)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..plots)
            self$.addOption(private$..signif)
            self$.addOption(private$..plotMetU)
            self$.addOption(private$..plotMetL)
            self$.addOption(private$..plotOrder)
            self$.addOption(private$..hclust)
            self$.addOption(private$..numClust)
            self$.addOption(private$..clustMet)
            self$.addOption(private$..clPos)
            self$.addOption(private$..clustCol)
            self$.addOption(private$..clustMan)
            self$.addOption(private$..clustMat)
            self$.addOption(private$..glasso)
            self$.addOption(private$..glassoTable)
            self$.addOption(private$..glassoPlot)
            self$.addOption(private$..glassoType)
            self$.addOption(private$..glassoGamma)
            self$.addOption(private$..glassoRho)
            self$.addOption(private$..glassoHub)
            self$.addOption(private$..glassoPlotScale)
            self$.addOption(private$..glassoLabels)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        selgroup = function() private$..selgroup$value,
        hyp = function() private$..hyp$value,
        method = function() private$..method$value,
        adjust = function() private$..adjust$value,
        tables = function() private$..tables$value,
        pval = function() private$..pval$value,
        flag = function() private$..flag$value,
        n = function() private$..n$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        plots = function() private$..plots$value,
        signif = function() private$..signif$value,
        plotMetU = function() private$..plotMetU$value,
        plotMetL = function() private$..plotMetL$value,
        plotOrder = function() private$..plotOrder$value,
        hclust = function() private$..hclust$value,
        numClust = function() private$..numClust$value,
        clustMet = function() private$..clustMet$value,
        clPos = function() private$..clPos$value,
        clustCol = function() private$..clustCol$value,
        clustMan = function() private$..clustMan$value,
        clustMat = function() private$..clustMat$value,
        glasso = function() private$..glasso$value,
        glassoTable = function() private$..glassoTable$value,
        glassoPlot = function() private$..glassoPlot$value,
        glassoType = function() private$..glassoType$value,
        glassoGamma = function() private$..glassoGamma$value,
        glassoRho = function() private$..glassoRho$value,
        glassoHub = function() private$..glassoHub$value,
        glassoPlotScale = function() private$..glassoPlotScale$value,
        glassoLabels = function() private$..glassoLabels$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..selgroup = NA,
        ..hyp = NA,
        ..method = NA,
        ..adjust = NA,
        ..tables = NA,
        ..pval = NA,
        ..flag = NA,
        ..n = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..plots = NA,
        ..signif = NA,
        ..plotMetU = NA,
        ..plotMetL = NA,
        ..plotOrder = NA,
        ..hclust = NA,
        ..numClust = NA,
        ..clustMet = NA,
        ..clPos = NA,
        ..clustCol = NA,
        ..clustMan = NA,
        ..clustMat = NA,
        ..glasso = NA,
        ..glassoTable = NA,
        ..glassoPlot = NA,
        ..glassoType = NA,
        ..glassoGamma = NA,
        ..glassoRho = NA,
        ..glassoHub = NA,
        ..glassoPlotScale = NA,
        ..glassoLabels = NA)
)

mCORResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mCORResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        matrix = function() private$.items[["matrix"]],
        treeplot = function() private$.items[["treeplot"]],
        plot = function() private$.items[["plot"]],
        rplots = function() private$.items[["rplots"]],
        glassoGroup = function() private$.items[["glassoGroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation clustering",
                refs=list(
                    "jys",
                    "corr"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Correlations",
                clearWith=list(
                    "group")))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                visible="(tables)",
                title="Correlation matrix",
                rows="(vars)",
                clearWith=list(
                    "ciWidth",
                    "hyp"),
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(method==\"pearson\")"),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="r", 
                        `visible`="(method==\"pearson\" && (ci || pval || n))"),
                    list(
                        `name`=".name[rho]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(method==\"spearman\")"),
                    list(
                        `name`=".stat[rho]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C1", 
                        `visible`="(method==\"spearman\" && (pval || n))"),
                    list(
                        `name`=".name[tau]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(method==\"kendall\")"),
                    list(
                        `name`=".stat[tau]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C4", 
                        `visible`="(method==\"kendall\" && (pval || n))"),
                    list(
                        `name`=".name[cil]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(method==\"pearson\" && ci)"),
                    list(
                        `name`=".stat[cil]", 
                        `title`="", 
                        `type`="text", 
                        `content`="CI Lower", 
                        `visible`="(method==\"pearson\" && ci)"),
                    list(
                        `name`=".name[ciu]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(method==\"pearson\" && ci)"),
                    list(
                        `name`=".stat[ciu]", 
                        `title`="", 
                        `type`="text", 
                        `content`="CI Upper", 
                        `visible`="(method==\"pearson\" && ci)"),
                    list(
                        `name`=".name[p]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(pval)"),
                    list(
                        `name`=".stat[p]", 
                        `title`="", 
                        `type`="text", 
                        `content`="p-value", 
                        `format`="zto,pvalue", 
                        `visible`="(pval)"),
                    list(
                        `name`=".name[n]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(n)"),
                    list(
                        `name`=".stat[n]", 
                        `title`="", 
                        `type`="text", 
                        `content`="N", 
                        `visible`="(n)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="treeplot",
                title="Hierarchical clustering tree",
                visible="(hclust)",
                width=500,
                height=400,
                renderFun=".treeplot",
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Correlation matrix",
                visible="(plots)",
                width=500,
                height=500,
                renderFun=".plot",
                requiresData=TRUE))
            self$add(jmvcore::Array$new(
                options=options,
                name="rplots",
                title="Intercluster Matrices",
                visible="(plots && clustMat)",
                template=jmvcore::Image$new(
                    options=options,
                    renderFun=".rplot",
                    requiresData=TRUE)))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    glassoTable = function() private$.items[["glassoTable"]],
                    glassoHubTable = function() private$.items[["glassoHubTable"]],
                    glassoPlot = function() private$.items[["glassoPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="glassoGroup",
                            title="Graphical Lasso (GLASSO) Partial Correlation Network",
                            refs=list(
                    "glasso",
                    "qgraph"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="glassoTable",
                            title="Partial correlation matrix",
                            visible="(glasso && glassoTable)",
                            rows="(vars)",
                            clearWith=list(
                                "glassoType",
                                "glassoGamma",
                                "glassoRho",
                                "vars",
                                "group",
                                "selgroup",
                                "method",
                                "pval",
                                "flag",
                                "n"),
                            columns=list(
                                list(
                                    `name`=".name[r]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(method==\"pearson\")"),
                                list(
                                    `name`=".stat[r]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="r", 
                                    `visible`="(method==\"pearson\" && (pval || n))"),
                                list(
                                    `name`=".name[rho]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(method==\"spearman\")"),
                                list(
                                    `name`=".stat[rho]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="\u03C1", 
                                    `visible`="(method==\"spearman\" && (pval || n))"),
                                list(
                                    `name`=".name[tau]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(method==\"kendall\")"),
                                list(
                                    `name`=".stat[tau]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="\u03C4", 
                                    `visible`="(method==\"kendall\" && (pval || n))"),
                                list(
                                    `name`=".name[p]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(pval)"),
                                list(
                                    `name`=".stat[p]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="p-value", 
                                    `format`="zto,pvalue", 
                                    `visible`="(pval)"),
                                list(
                                    `name`=".name[n]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)", 
                                    `combineBelow`=TRUE, 
                                    `visible`="(n)"),
                                list(
                                    `name`=".stat[n]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="N", 
                                    `visible`="(n)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="glassoHubTable",
                            title="Centrality metrics (hub markers)",
                            visible="(glasso && glassoHub)",
                            clearWith=list(
                                "glassoType",
                                "glassoGamma",
                                "glassoRho",
                                "vars",
                                "group",
                                "selgroup",
                                "method"),
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="strength", 
                                    `title`="Strength", 
                                    `type`="number"),
                                list(
                                    `name`="closeness", 
                                    `title`="Closeness", 
                                    `type`="number"),
                                list(
                                    `name`="betweenness", 
                                    `title`="Betweenness", 
                                    `type`="number"),
                                list(
                                    `name`="influence", 
                                    `title`="Expected Influence", 
                                    `type`="number"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="glassoPlot",
                            title="Network plot",
                            visible="(glasso && glassoPlot)",
                            width=500,
                            height=500,
                            renderFun=".glassoPlot",
                            requiresData=TRUE,
                            clearWith=list(
                                "glassoType",
                                "glassoGamma",
                                "glassoRho",
                                "vars",
                                "group",
                                "selgroup",
                                "glassoPlotScale",
                                "glassoLabels",
                                "hclust",
                                "numClust",
                                "clustMet",
                                "clustCol",
                                "clustMan",
                                "method")))}))$new(options=options))}))

mCORBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mCORBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mCOR",
                version = c(1,1,1),
                options = options,
                results = mCORResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correlation clustering
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param selgroup .
#' @param hyp .
#' @param method .
#' @param adjust .
#' @param tables .
#' @param pval .
#' @param flag .
#' @param n .
#' @param ci .
#' @param ciWidth .
#' @param plots \code{TRUE} or \code{FALSE} (default), provide a correlation
#'   matrix plot
#' @param signif .
#' @param plotMetU .
#' @param plotMetL .
#' @param plotOrder .
#' @param hclust .
#' @param numClust .
#' @param clustMet .
#' @param clPos .
#' @param clustCol .
#' @param clustMan .
#' @param clustMat .
#' @param glasso .
#' @param glassoTable .
#' @param glassoPlot .
#' @param glassoType .
#' @param glassoGamma .
#' @param glassoRho .
#' @param glassoHub .
#' @param glassoPlotScale .
#' @param glassoLabels .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a correlation matrix table \cr
#'   \code{results$treeplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$rplots} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$glassoGroup$glassoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$glassoGroup$glassoHubTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$glassoGroup$glassoPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
mCOR <- function(
    data,
    vars,
    group,
    selgroup,
    hyp = "corr",
    method = "pearson",
    adjust = "none",
    tables = TRUE,
    pval = TRUE,
    flag = FALSE,
    n = FALSE,
    ci = FALSE,
    ciWidth = 95,
    plots = FALSE,
    signif = "all",
    plotMetU = "ellipse",
    plotMetL = "ellipse",
    plotOrder = "original",
    hclust = FALSE,
    numClust = 2,
    clustMet = "ward.D2",
    clPos = "b",
    clustCol = FALSE,
    clustMan = "",
    clustMat = FALSE,
    glasso = FALSE,
    glassoTable = FALSE,
    glassoPlot = TRUE,
    glassoType = "ebic",
    glassoGamma = 0.5,
    glassoRho = 0.1,
    glassoHub = FALSE,
    glassoPlotScale = TRUE,
    glassoLabels = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mCOR requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mCOROptions$new(
        vars = vars,
        group = group,
        selgroup = selgroup,
        hyp = hyp,
        method = method,
        adjust = adjust,
        tables = tables,
        pval = pval,
        flag = flag,
        n = n,
        ci = ci,
        ciWidth = ciWidth,
        plots = plots,
        signif = signif,
        plotMetU = plotMetU,
        plotMetL = plotMetL,
        plotOrder = plotOrder,
        hclust = hclust,
        numClust = numClust,
        clustMet = clustMet,
        clPos = clPos,
        clustCol = clustCol,
        clustMan = clustMan,
        clustMat = clustMat,
        glasso = glasso,
        glassoTable = glassoTable,
        glassoPlot = glassoPlot,
        glassoType = glassoType,
        glassoGamma = glassoGamma,
        glassoRho = glassoRho,
        glassoHub = glassoHub,
        glassoPlotScale = glassoPlotScale,
        glassoLabels = glassoLabels)

    analysis <- mCORClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

