
# This file is automatically generated, you probably don't want to edit this

mDCAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mDCAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            targetLevel = NULL,
            probs = NULL,
            scores = list(),
            threshMin = 0.01,
            threshMax = 0.5,
            threshStep = 0.01,
            harm = 0,
            showDcaTable = TRUE,
            showWindowTable = TRUE,
            showDcaPlot = TRUE,
            showAvoidedPlot = TRUE,
            showCalTable = TRUE,
            showCalPlot = FALSE,
            calBins = 10,
            recalibrate = FALSE,
            palBrewer = "Dark2", ...) {

            super$initialize(
                package="jYS",
                name="mDCA",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                required=TRUE)
            private$..targetLevel <- jmvcore::OptionLevel$new(
                "targetLevel",
                targetLevel,
                variable="(dep)")
            private$..probs <- jmvcore::OptionVariables$new(
                "probs",
                probs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                required=TRUE)
            private$..scores <- jmvcore::OptionVariables$new(
                "scores",
                scores,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=list())
            private$..threshMin <- jmvcore::OptionNumber$new(
                "threshMin",
                threshMin,
                min=0.001,
                max=0.5,
                default=0.01)
            private$..threshMax <- jmvcore::OptionNumber$new(
                "threshMax",
                threshMax,
                min=0.1,
                max=0.99,
                default=0.5)
            private$..threshStep <- jmvcore::OptionNumber$new(
                "threshStep",
                threshStep,
                min=0.005,
                max=0.1,
                default=0.01)
            private$..harm <- jmvcore::OptionNumber$new(
                "harm",
                harm,
                default=0)
            private$..showDcaTable <- jmvcore::OptionBool$new(
                "showDcaTable",
                showDcaTable,
                default=TRUE)
            private$..showWindowTable <- jmvcore::OptionBool$new(
                "showWindowTable",
                showWindowTable,
                default=TRUE)
            private$..showDcaPlot <- jmvcore::OptionBool$new(
                "showDcaPlot",
                showDcaPlot,
                default=TRUE)
            private$..showAvoidedPlot <- jmvcore::OptionBool$new(
                "showAvoidedPlot",
                showAvoidedPlot,
                default=TRUE)
            private$..showCalTable <- jmvcore::OptionBool$new(
                "showCalTable",
                showCalTable,
                default=TRUE)
            private$..showCalPlot <- jmvcore::OptionBool$new(
                "showCalPlot",
                showCalPlot,
                default=FALSE)
            private$..calBins <- jmvcore::OptionInteger$new(
                "calBins",
                calBins,
                min=4,
                max=20,
                default=10)
            private$..recalibrate <- jmvcore::OptionBool$new(
                "recalibrate",
                recalibrate,
                default=FALSE)
            private$..palBrewer <- jmvcore::OptionList$new(
                "palBrewer",
                palBrewer,
                options=list(
                    "Dark2",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Paired",
                    "Accent"),
                default="Dark2")

            self$.addOption(private$..dep)
            self$.addOption(private$..targetLevel)
            self$.addOption(private$..probs)
            self$.addOption(private$..scores)
            self$.addOption(private$..threshMin)
            self$.addOption(private$..threshMax)
            self$.addOption(private$..threshStep)
            self$.addOption(private$..harm)
            self$.addOption(private$..showDcaTable)
            self$.addOption(private$..showWindowTable)
            self$.addOption(private$..showDcaPlot)
            self$.addOption(private$..showAvoidedPlot)
            self$.addOption(private$..showCalTable)
            self$.addOption(private$..showCalPlot)
            self$.addOption(private$..calBins)
            self$.addOption(private$..recalibrate)
            self$.addOption(private$..palBrewer)
        }),
    active = list(
        dep = function() private$..dep$value,
        targetLevel = function() private$..targetLevel$value,
        probs = function() private$..probs$value,
        scores = function() private$..scores$value,
        threshMin = function() private$..threshMin$value,
        threshMax = function() private$..threshMax$value,
        threshStep = function() private$..threshStep$value,
        harm = function() private$..harm$value,
        showDcaTable = function() private$..showDcaTable$value,
        showWindowTable = function() private$..showWindowTable$value,
        showDcaPlot = function() private$..showDcaPlot$value,
        showAvoidedPlot = function() private$..showAvoidedPlot$value,
        showCalTable = function() private$..showCalTable$value,
        showCalPlot = function() private$..showCalPlot$value,
        calBins = function() private$..calBins$value,
        recalibrate = function() private$..recalibrate$value,
        palBrewer = function() private$..palBrewer$value),
    private = list(
        ..dep = NA,
        ..targetLevel = NA,
        ..probs = NA,
        ..scores = NA,
        ..threshMin = NA,
        ..threshMax = NA,
        ..threshStep = NA,
        ..harm = NA,
        ..showDcaTable = NA,
        ..showWindowTable = NA,
        ..showDcaPlot = NA,
        ..showAvoidedPlot = NA,
        ..showCalTable = NA,
        ..showCalPlot = NA,
        ..calBins = NA,
        ..recalibrate = NA,
        ..palBrewer = NA)
)

mDCAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mDCAResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        dcaTable = function() private$.items[["dcaTable"]],
        windowTable = function() private$.items[["windowTable"]],
        dcaPlot = function() private$.items[["dcaPlot"]],
        avoidedPlot = function() private$.items[["avoidedPlot"]],
        calTable = function() private$.items[["calTable"]],
        calPlot = function() private$.items[["calPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Decision Curve Analysis (DCA)",
                refs=list(
                    "jys",
                    "vickers2006",
                    "vickers2016"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcaTable",
                title="Net Benefit at Key Clinical Thresholds",
                visible="(showDcaTable)",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "threshMin",
                    "threshMax",
                    "threshStep",
                    "harm",
                    "recalibrate"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model / Predictor", 
                        `type`="text"),
                    list(
                        `name`="nb_10", 
                        `title`="NB at 10%", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="nb_20", 
                        `title`="NB at 20%", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="nb_30", 
                        `title`="NB at 30%", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="nb_40", 
                        `title`="NB at 40%", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="max_nb", 
                        `title`="Max Net Benefit", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="opt_thresh", 
                        `title`="Optimal Threshold", 
                        `type`="number", 
                        `format`="zto,dp:2"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="windowTable",
                title="Clinical Decision Window",
                visible="(showWindowTable)",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "threshMin",
                    "threshMax",
                    "threshStep",
                    "harm",
                    "recalibrate"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model / Predictor", 
                        `type`="text"),
                    list(
                        `name`="min_thresh", 
                        `title`="Min Threshold (%)", 
                        `type`="number", 
                        `format`="zto,dp:1"),
                    list(
                        `name`="max_thresh", 
                        `title`="Max Threshold (%)", 
                        `type`="number", 
                        `format`="zto,dp:1"),
                    list(
                        `name`="window_span", 
                        `title`="Window Span (%)", 
                        `type`="number", 
                        `format`="zto,dp:1"),
                    list(
                        `name`="avoid_20", 
                        `title`="Avoided at 20% (per 100)", 
                        `type`="number", 
                        `format`="zto,dp:1"),
                    list(
                        `name`="status", 
                        `title`="Clinical Superiority", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="dcaPlot",
                title="Decision Curves (Net Benefit vs Threshold)",
                visible="(showDcaPlot)",
                width=650,
                height=450,
                renderFun=".dcaPlot",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "threshMin",
                    "threshMax",
                    "threshStep",
                    "harm",
                    "recalibrate",
                    "palBrewer")))
            self$add(jmvcore::Image$new(
                options=options,
                name="avoidedPlot",
                title="Net Reduction in Interventions (per 100 patients)",
                visible="(showAvoidedPlot)",
                width=650,
                height=420,
                renderFun=".avoidedPlot",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "threshMin",
                    "threshMax",
                    "threshStep",
                    "harm",
                    "recalibrate",
                    "palBrewer")))
            self$add(jmvcore::Table$new(
                options=options,
                name="calTable",
                title="Model Calibration Metrics",
                visible="(showCalTable)",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "recalibrate",
                    "calBins"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="brier", 
                        `title`="Brier Score", 
                        `type`="number", 
                        `format`="zto,dp:4"),
                    list(
                        `name`="slope", 
                        `title`="Calibration Slope", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="intercept", 
                        `title`="Calibration Intercept", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="e_avg", 
                        `title`="E avg", 
                        `type`="number", 
                        `format`="zto,dp:3"),
                    list(
                        `name`="e_max", 
                        `title`="E max", 
                        `type`="number", 
                        `format`="zto,dp:3"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="calPlot",
                title="Model Calibration Curves (Observed vs Predicted)",
                visible="(showCalPlot)",
                width=600,
                height=450,
                renderFun=".calPlot",
                clearWith=list(
                    "dep",
                    "targetLevel",
                    "probs",
                    "scores",
                    "recalibrate",
                    "calBins",
                    "palBrewer")))}))

mDCABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mDCABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mDCA",
                version = c(1,0,0),
                options = options,
                results = mDCAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Decision Curve Analysis (DCA)
#'
#' Decision Curve Analysis (DCA) and Model Calibration. Evaluates clinical net 
#' benefit (Vickers et al., 2006) and interventions avoided for predictive 
#' models and biomarkers.
#' @param data .
#' @param dep .
#' @param targetLevel .
#' @param probs .
#' @param scores .
#' @param threshMin .
#' @param threshMax .
#' @param threshStep .
#' @param harm .
#' @param showDcaTable .
#' @param showWindowTable .
#' @param showDcaPlot .
#' @param showAvoidedPlot .
#' @param showCalTable .
#' @param showCalPlot .
#' @param calBins .
#' @param recalibrate .
#' @param palBrewer .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dcaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$windowTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcaPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$avoidedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$calTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$calPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dcaTable$asDF}
#'
#' \code{as.data.frame(results$dcaTable)}
#'
#' @export
mDCA <- function(
    data,
    dep,
    targetLevel,
    probs,
    scores = list(),
    threshMin = 0.01,
    threshMax = 0.5,
    threshStep = 0.01,
    harm = 0,
    showDcaTable = TRUE,
    showWindowTable = TRUE,
    showDcaPlot = TRUE,
    showAvoidedPlot = TRUE,
    showCalTable = TRUE,
    showCalPlot = FALSE,
    calBins = 10,
    recalibrate = FALSE,
    palBrewer = "Dark2") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mDCA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(probs)) probs <- jmvcore::resolveQuo(jmvcore::enquo(probs))
    if ( ! missing(scores)) scores <- jmvcore::resolveQuo(jmvcore::enquo(scores))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(probs), probs, NULL),
            `if`( ! missing(scores), scores, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mDCAOptions$new(
        dep = dep,
        targetLevel = targetLevel,
        probs = probs,
        scores = scores,
        threshMin = threshMin,
        threshMax = threshMax,
        threshStep = threshStep,
        harm = harm,
        showDcaTable = showDcaTable,
        showWindowTable = showWindowTable,
        showDcaPlot = showDcaPlot,
        showAvoidedPlot = showAvoidedPlot,
        showCalTable = showCalTable,
        showCalPlot = showCalPlot,
        calBins = calBins,
        recalibrate = recalibrate,
        palBrewer = palBrewer)

    analysis <- mDCAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

