
# This file is automatically generated, you probably don't want to edit this

mMFOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMFOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            learnvar = NULL,
            imputevar = NULL,
            maxiter = 10,
            ntree = 100, ...) {

            super$initialize(
                package="jYS",
                name="mMF",
                requiresData=TRUE,
                ...)

            private$..learnvar <- jmvcore::OptionVariables$new(
                "learnvar",
                learnvar,
                required=FALSE)
            private$..imputevar <- jmvcore::OptionVariables$new(
                "imputevar",
                imputevar,
                takeFromDataIfMissing=TRUE,
                required=TRUE)
            private$..maxiter <- jmvcore::OptionNumber$new(
                "maxiter",
                maxiter,
                default=10)
            private$..ntree <- jmvcore::OptionNumber$new(
                "ntree",
                ntree,
                default=100)
            private$..imputeOV <- jmvcore::OptionOutput$new(
                "imputeOV")

            self$.addOption(private$..learnvar)
            self$.addOption(private$..imputevar)
            self$.addOption(private$..maxiter)
            self$.addOption(private$..ntree)
            self$.addOption(private$..imputeOV)
        }),
    active = list(
        learnvar = function() private$..learnvar$value,
        imputevar = function() private$..imputevar$value,
        maxiter = function() private$..maxiter$value,
        ntree = function() private$..ntree$value,
        imputeOV = function() private$..imputeOV$value),
    private = list(
        ..learnvar = NA,
        ..imputevar = NA,
        ..maxiter = NA,
        ..ntree = NA,
        ..imputeOV = NA)
)

mMFResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMFResults",
    inherit = jmvcore::Group,
    active = list(
        errors = function() private$.items[["errors"]],
        imputeOV = function() private$.items[["imputeOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Missing Values Imputation",
                refs=list(
                    "mf",
                    "impr"))
            self$add(jmvcore::Table$new(
                options=options,
                name="errors",
                visible="(imputeOV)",
                title="Estimated out-of-bag (OOB) imputation error",
                rows="(imputevar)",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Variable", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="ninp", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mse", 
                        `title`="MSE", 
                        `type`="number"),
                    list(
                        `name`="pfc", 
                        `title`="PFC", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputeOV",
                title="Imputed misses"))}))

mMFBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMFBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mMF",
                version = c(1,0,5),
                options = options,
                results = mMFResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Missing Values Imputation
#'
#' 
#' @param data .
#' @param learnvar .
#' @param imputevar .
#' @param maxiter .
#' @param ntree .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$errors} \tab \tab \tab \tab \tab OOB errors table \cr
#'   \code{results$imputeOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$errors$asDF}
#'
#' \code{as.data.frame(results$errors)}
#'
#' @export
mMF <- function(
    data,
    learnvar,
    imputevar,
    maxiter = 10,
    ntree = 100) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mMF requires jmvcore to be installed (restart may be required)")

    if ( ! missing(learnvar)) learnvar <- jmvcore::resolveQuo(jmvcore::enquo(learnvar))
    if ( ! missing(imputevar)) imputevar <- jmvcore::resolveQuo(jmvcore::enquo(imputevar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(learnvar), learnvar, NULL),
            `if`( ! missing(imputevar), imputevar, NULL))

    imputevar <- `if`( ! missing(imputevar), imputevar, colnames(data))

    options <- mMFOptions$new(
        learnvar = learnvar,
        imputevar = imputevar,
        maxiter = maxiter,
        ntree = ntree)

    analysis <- mMFClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

