
# This file is automatically generated, you probably don't want to edit this

mMLPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMLPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            hidden_structure = "10,5",
            activation = "relu",
            out_activation = "sigmoid",
            decay = 0.1,
            maxit = 100,
            rang = 0.7,
            partition = "kfold",
            val_split = 30,
            cv_folds = 5,
            show_imp = FALSE,
            show_topo = FALSE,
            show_curve = FALSE,
            show_matrix = FALSE,
            show_roc = FALSE,
            roc_x = "1spec",
            roc_unit = "percent",
            multiclass_roc_type = "combined",
            palBrewer = "Dark2", ...) {

            super$initialize(
                package="jYS",
                name="mMLP",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                required=TRUE)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..hidden_structure <- jmvcore::OptionString$new(
                "hidden_structure",
                hidden_structure,
                default="10,5")
            private$..activation <- jmvcore::OptionList$new(
                "activation",
                activation,
                options=list(
                    "relu",
                    "sigmoid",
                    "tanh",
                    "softmax"),
                default="relu")
            private$..out_activation <- jmvcore::OptionList$new(
                "out_activation",
                out_activation,
                options=list(
                    "sigmoid",
                    "identity",
                    "softmax"),
                default="sigmoid")
            private$..decay <- jmvcore::OptionNumber$new(
                "decay",
                decay,
                min=0,
                default=0.1)
            private$..maxit <- jmvcore::OptionInteger$new(
                "maxit",
                maxit,
                min=10,
                default=100)
            private$..rang <- jmvcore::OptionNumber$new(
                "rang",
                rang,
                min=0.01,
                default=0.7)
            private$..partition <- jmvcore::OptionList$new(
                "partition",
                partition,
                options=list(
                    "holdout",
                    "kfold"),
                default="kfold")
            private$..val_split <- jmvcore::OptionNumber$new(
                "val_split",
                val_split,
                min=10,
                max=90,
                default=30)
            private$..cv_folds <- jmvcore::OptionInteger$new(
                "cv_folds",
                cv_folds,
                min=2,
                max=20,
                default=5)
            private$..show_imp <- jmvcore::OptionBool$new(
                "show_imp",
                show_imp,
                default=FALSE)
            private$..show_topo <- jmvcore::OptionBool$new(
                "show_topo",
                show_topo,
                default=FALSE)
            private$..show_curve <- jmvcore::OptionBool$new(
                "show_curve",
                show_curve,
                default=FALSE)
            private$..show_matrix <- jmvcore::OptionBool$new(
                "show_matrix",
                show_matrix,
                default=FALSE)
            private$..show_roc <- jmvcore::OptionBool$new(
                "show_roc",
                show_roc,
                default=FALSE)
            private$..roc_x <- jmvcore::OptionList$new(
                "roc_x",
                roc_x,
                options=list(
                    "spec",
                    "1spec"),
                default="1spec")
            private$..roc_unit <- jmvcore::OptionList$new(
                "roc_unit",
                roc_unit,
                options=list(
                    "decimal",
                    "percent"),
                default="percent")
            private$..multiclass_roc_type <- jmvcore::OptionList$new(
                "multiclass_roc_type",
                multiclass_roc_type,
                options=list(
                    "combined",
                    "separate"),
                default="combined")
            private$..palBrewer <- jmvcore::OptionList$new(
                "palBrewer",
                palBrewer,
                options=list(
                    "none",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Dark2")
            private$..predClass <- jmvcore::OptionOutput$new(
                "predClass")
            private$..predProb <- jmvcore::OptionOutput$new(
                "predProb")

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..hidden_structure)
            self$.addOption(private$..activation)
            self$.addOption(private$..out_activation)
            self$.addOption(private$..decay)
            self$.addOption(private$..maxit)
            self$.addOption(private$..rang)
            self$.addOption(private$..partition)
            self$.addOption(private$..val_split)
            self$.addOption(private$..cv_folds)
            self$.addOption(private$..show_imp)
            self$.addOption(private$..show_topo)
            self$.addOption(private$..show_curve)
            self$.addOption(private$..show_matrix)
            self$.addOption(private$..show_roc)
            self$.addOption(private$..roc_x)
            self$.addOption(private$..roc_unit)
            self$.addOption(private$..multiclass_roc_type)
            self$.addOption(private$..palBrewer)
            self$.addOption(private$..predClass)
            self$.addOption(private$..predProb)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        hidden_structure = function() private$..hidden_structure$value,
        activation = function() private$..activation$value,
        out_activation = function() private$..out_activation$value,
        decay = function() private$..decay$value,
        maxit = function() private$..maxit$value,
        rang = function() private$..rang$value,
        partition = function() private$..partition$value,
        val_split = function() private$..val_split$value,
        cv_folds = function() private$..cv_folds$value,
        show_imp = function() private$..show_imp$value,
        show_topo = function() private$..show_topo$value,
        show_curve = function() private$..show_curve$value,
        show_matrix = function() private$..show_matrix$value,
        show_roc = function() private$..show_roc$value,
        roc_x = function() private$..roc_x$value,
        roc_unit = function() private$..roc_unit$value,
        multiclass_roc_type = function() private$..multiclass_roc_type$value,
        palBrewer = function() private$..palBrewer$value,
        predClass = function() private$..predClass$value,
        predProb = function() private$..predProb$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..hidden_structure = NA,
        ..activation = NA,
        ..out_activation = NA,
        ..decay = NA,
        ..maxit = NA,
        ..rang = NA,
        ..partition = NA,
        ..val_split = NA,
        ..cv_folds = NA,
        ..show_imp = NA,
        ..show_topo = NA,
        ..show_curve = NA,
        ..show_matrix = NA,
        ..show_roc = NA,
        ..roc_x = NA,
        ..roc_unit = NA,
        ..multiclass_roc_type = NA,
        ..palBrewer = NA,
        ..predClass = NA,
        ..predProb = NA)
)

mMLPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMLPResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        infoTable = function() private$.items[["infoTable"]],
        importanceTable = function() private$.items[["importanceTable"]],
        importancePlot = function() private$.items[["importancePlot"]],
        topoPlot = function() private$.items[["topoPlot"]],
        curvePlot = function() private$.items[["curvePlot"]],
        matrixTable = function() private$.items[["matrixTable"]],
        statsTable = function() private$.items[["statsTable"]],
        rocPlot = function() private$.items[["rocPlot"]],
        predClass = function() private$.items[["predClass"]],
        predProb = function() private$.items[["predProb"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MLP Classifier",
                refs=list(
                    "jys",
                    "rip",
                    "bish",
                    "adam"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Conditions",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="infoTable",
                title="Model Information & Accuracy",
                rows=6,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="importanceTable",
                title="Predictor Importance",
                visible="(show_imp)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="imp", 
                        `title`="Mean Decrease in Accuracy", 
                        `type`="number"),
                    list(
                        `name`="rank", 
                        `title`="Rank", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="importancePlot",
                title="Predictor Importance Chart",
                visible="(show_imp)",
                width=500,
                height=350,
                renderFun=".importancePlot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="topoPlot",
                title="MLP Network Topology",
                visible="(show_topo)",
                width=600,
                height=500,
                renderFun=".topoPlot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="curvePlot",
                title="MLP Learning Curve",
                visible="(show_curve)",
                width=500,
                height=350,
                renderFun=".curvePlot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "val_split")))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrixTable",
                title="Confusion Matrix",
                visible="(show_matrix)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds"),
                columns=list(
                    list(
                        `name`="actual", 
                        `title`="Actual Class", 
                        `type`="text"),
                    list(
                        `name`="predicted", 
                        `title`="Predicted Class", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="statsTable",
                title="Performance Statistics",
                visible="(show_matrix)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="trainVal", 
                        `title`="Training", 
                        `type`="number"),
                    list(
                        `name`="cvVal", 
                        `title`="Validation", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="rocPlot",
                title="ROC Analysis Comparison",
                visible="(show_roc)",
                template=jmvcore::Image$new(
                    options=options,
                    width=500,
                    height=500,
                    renderFun=".rocPlot",
                    requiresData=TRUE),
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "roc_x",
                    "roc_unit",
                    "multiclass_roc_type",
                    "palBrewer")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predClass",
                title="Predicted Class",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predProb",
                title="Predicted Probability",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "hidden_structure",
                    "activation",
                    "out_activation",
                    "decay",
                    "maxit",
                    "rang",
                    "partition",
                    "val_split",
                    "cv_folds")))}))

mMLPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMLPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mMLP",
                version = c(1,1,0),
                options = options,
                results = mMLPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' MLP Classifier
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param hidden_structure .
#' @param activation .
#' @param out_activation .
#' @param decay .
#' @param maxit .
#' @param rang .
#' @param partition .
#' @param val_split .
#' @param cv_folds .
#' @param show_imp .
#' @param show_topo .
#' @param show_curve .
#' @param show_matrix .
#' @param show_roc .
#' @param roc_x .
#' @param roc_unit .
#' @param multiclass_roc_type .
#' @param palBrewer .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$importanceTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$importancePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$topoPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$curvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$matrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$statsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rocPlot} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$predClass} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predProb} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infoTable$asDF}
#'
#' \code{as.data.frame(results$infoTable)}
#'
#' @export
mMLP <- function(
    data,
    dep,
    covs,
    factors,
    hidden_structure = "10,5",
    activation = "relu",
    out_activation = "sigmoid",
    decay = 0.1,
    maxit = 100,
    rang = 0.7,
    partition = "kfold",
    val_split = 30,
    cv_folds = 5,
    show_imp = FALSE,
    show_topo = FALSE,
    show_curve = FALSE,
    show_matrix = FALSE,
    show_roc = FALSE,
    roc_x = "1spec",
    roc_unit = "percent",
    multiclass_roc_type = "combined",
    palBrewer = "Dark2") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mMLP requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mMLPOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        hidden_structure = hidden_structure,
        activation = activation,
        out_activation = out_activation,
        decay = decay,
        maxit = maxit,
        rang = rang,
        partition = partition,
        val_split = val_split,
        cv_folds = cv_folds,
        show_imp = show_imp,
        show_topo = show_topo,
        show_curve = show_curve,
        show_matrix = show_matrix,
        show_roc = show_roc,
        roc_x = roc_x,
        roc_unit = roc_unit,
        multiclass_roc_type = multiclass_roc_type,
        palBrewer = palBrewer)

    analysis <- mMLPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

