
# This file is automatically generated, you probably don't want to edit this

mMOUTOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMOUTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            method = "robust",
            alpha = "0.01",
            showPlots = TRUE,
            plotType = "both",
            outind = TRUE, ...) {

            super$initialize(
                package="jYS",
                name="mMOUT",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "classic",
                    "robust"),
                default="robust")
            private$..alpha <- jmvcore::OptionList$new(
                "alpha",
                alpha,
                options=list(
                    "0.05",
                    "0.01",
                    "0.001"),
                default="0.01")
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..plotType <- jmvcore::OptionList$new(
                "plotType",
                plotType,
                options=list(
                    "dd",
                    "qq",
                    "both"),
                default="both")
            private$..outind <- jmvcore::OptionBool$new(
                "outind",
                outind,
                default=TRUE)
            private$..outDist <- jmvcore::OptionOutput$new(
                "outDist")
            private$..outFlag <- jmvcore::OptionOutput$new(
                "outFlag")
            private$..remOut <- jmvcore::OptionOutput$new(
                "remOut")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..method)
            self$.addOption(private$..alpha)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotType)
            self$.addOption(private$..outind)
            self$.addOption(private$..outDist)
            self$.addOption(private$..outFlag)
            self$.addOption(private$..remOut)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        method = function() private$..method$value,
        alpha = function() private$..alpha$value,
        showPlots = function() private$..showPlots$value,
        plotType = function() private$..plotType$value,
        outind = function() private$..outind$value,
        outDist = function() private$..outDist$value,
        outFlag = function() private$..outFlag$value,
        remOut = function() private$..remOut$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..method = NA,
        ..alpha = NA,
        ..showPlots = NA,
        ..plotType = NA,
        ..outind = NA,
        ..outDist = NA,
        ..outFlag = NA,
        ..remOut = NA)
)

mMOUTResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMOUTResults",
    inherit = jmvcore::Group,
    active = list(
        outDist = function() private$.items[["outDist"]],
        outFlag = function() private$.items[["outFlag"]],
        remOut = function() private$.items[["remOut"]],
        stat = function() private$.items[["stat"]],
        oind = function() private$.items[["oind"]],
        ddplot = function() private$.items[["ddplot"]],
        qqplot = function() private$.items[["qqplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariate outliers identification and removal",
                refs=list(
                    "jys"))
            self$add(jmvcore::Output$new(
                options=options,
                name="outDist",
                title="Saved Mahalanobis distances"))
            self$add(jmvcore::Output$new(
                options=options,
                name="outFlag",
                title="Saved outlier flags"))
            self$add(jmvcore::Output$new(
                options=options,
                name="remOut",
                title="Remove outliers"))
            self$add(jmvcore::Table$new(
                options=options,
                name="stat",
                title="Outliers summary",
                clearWith=list(
                    "vars",
                    "group",
                    "method",
                    "alpha"),
                columns=list(
                    list(
                        `name`="grp", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="noutl", 
                        `title`="Outliers found", 
                        `type`="integer"),
                    list(
                        `name`="pct", 
                        `title`="% Outliers", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="cutoff", 
                        `title`="Chi-Square Cut-off", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="oind",
                title="Outliers indices (Rows)",
                visible="(outind)",
                clearWith=list(
                    "vars",
                    "group",
                    "method",
                    "alpha"),
                columns=list(
                    list(
                        `name`="grp", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="count", 
                        `title`="Outliers found", 
                        `type`="integer"),
                    list(
                        `name`="indices", 
                        `title`="Indices", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="ddplot",
                title="Distance-Distance Plot",
                width=550,
                height=450,
                renderFun=".plotDD",
                requiresData=TRUE,
                visible="(showPlots && (plotType == \"dd\" || plotType == \"both\"))",
                clearWith=list(
                    "vars",
                    "group",
                    "method",
                    "alpha")))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqplot",
                title="Chi-Square Q-Q Plot",
                width=550,
                height=450,
                renderFun=".plotQQ",
                requiresData=TRUE,
                visible="(showPlots && (plotType == \"qq\" || plotType == \"both\"))",
                clearWith=list(
                    "vars",
                    "group",
                    "method",
                    "alpha")))}))

mMOUTBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mMOUTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mMOUT",
                version = c(1,0,0),
                options = options,
                results = mMOUTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multivariate outliers identification and removal
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param method .
#' @param alpha .
#' @param showPlots .
#' @param plotType .
#' @param outind .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$outDist} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outFlag} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$remOut} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$stat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$oind} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ddplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qqplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$stat$asDF}
#'
#' \code{as.data.frame(results$stat)}
#'
#' @export
mMOUT <- function(
    data,
    vars,
    group,
    method = "robust",
    alpha = "0.01",
    showPlots = TRUE,
    plotType = "both",
    outind = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mMOUT requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mMOUTOptions$new(
        vars = vars,
        group = group,
        method = method,
        alpha = alpha,
        showPlots = showPlots,
        plotType = plotType,
        outind = outind)

    analysis <- mMOUTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

