
# This file is automatically generated, you probably don't want to edit this

mOUTOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mOUTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            boxpl = FALSE,
            outlcheck = "IQR",
            fence = "1.5",
            tholdZS = "3.0",
            tholdmZS = "3.5",
            outfence = TRUE,
            norm = FALSE,
            outind = FALSE, ...) {

            super$initialize(
                package="jYS",
                name="mOUT",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..remOut <- jmvcore::OptionOutput$new(
                "remOut")
            private$..boxpl <- jmvcore::OptionBool$new(
                "boxpl",
                boxpl,
                default=FALSE)
            private$..outlcheck <- jmvcore::OptionList$new(
                "outlcheck",
                outlcheck,
                options=list(
                    "IQR",
                    "ZS",
                    "mZS"),
                default="IQR")
            private$..fence <- jmvcore::OptionList$new(
                "fence",
                fence,
                options=list(
                    "1.5",
                    "2.2",
                    "3.0"),
                default="1.5")
            private$..tholdZS <- jmvcore::OptionList$new(
                "tholdZS",
                tholdZS,
                options=list(
                    "2.5",
                    "3.0",
                    "3.5",
                    "4.0",
                    "4.5",
                    "5.0"),
                default="3.0")
            private$..tholdmZS <- jmvcore::OptionList$new(
                "tholdmZS",
                tholdmZS,
                options=list(
                    "2.5",
                    "3.0",
                    "3.5",
                    "4.0",
                    "4.5",
                    "5.0"),
                default="3.5")
            private$..outfence <- jmvcore::OptionBool$new(
                "outfence",
                outfence,
                default=TRUE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=FALSE)
            private$..outind <- jmvcore::OptionBool$new(
                "outind",
                outind,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..remOut)
            self$.addOption(private$..boxpl)
            self$.addOption(private$..outlcheck)
            self$.addOption(private$..fence)
            self$.addOption(private$..tholdZS)
            self$.addOption(private$..tholdmZS)
            self$.addOption(private$..outfence)
            self$.addOption(private$..norm)
            self$.addOption(private$..outind)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        remOut = function() private$..remOut$value,
        boxpl = function() private$..boxpl$value,
        outlcheck = function() private$..outlcheck$value,
        fence = function() private$..fence$value,
        tholdZS = function() private$..tholdZS$value,
        tholdmZS = function() private$..tholdmZS$value,
        outfence = function() private$..outfence$value,
        norm = function() private$..norm$value,
        outind = function() private$..outind$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..remOut = NA,
        ..boxpl = NA,
        ..outlcheck = NA,
        ..fence = NA,
        ..tholdZS = NA,
        ..tholdmZS = NA,
        ..outfence = NA,
        ..norm = NA,
        ..outind = NA)
)

mOUTResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mOUTResults",
    inherit = jmvcore::Group,
    active = list(
        remOut = function() private$.items[["remOut"]],
        stat = function() private$.items[["stat"]],
        oind = function() private$.items[["oind"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Univariate outliers identification and removal",
                refs=list(
                    "jys"))
            self$add(jmvcore::Output$new(
                options=options,
                name="remOut",
                title="Remove outliers"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    outstat = function() private$.items[["outstat"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="stat",
                            title="Outliers identification")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="outstat",
                            title="Outliers fences",
                            visible="(outfence)",
                            clearWith=list(
                                "vars",
                                "group"),
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="Variable", 
                                    `type`="text"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="oind",
                title="Outliers indices",
                visible="(outind)",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    columns=list())))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Boxplots with outliers",
                visible="(boxpl)",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plot",
                    requiresData=TRUE)))}))

mOUTBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mOUTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mOUT",
                version = c(1,0,10),
                options = options,
                results = mOUTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Univariate outliers identification and removal
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param boxpl .
#' @param outlcheck .
#' @param fence .
#' @param tholdZS .
#' @param tholdmZS .
#' @param outfence .
#' @param norm .
#' @param outind .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$remOut} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$stat$outstat} \tab \tab \tab \tab \tab Calculated fences for outliers \cr
#'   \code{results$oind} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
mOUT <- function(
    data,
    vars,
    group,
    boxpl = FALSE,
    outlcheck = "IQR",
    fence = "1.5",
    tholdZS = "3.0",
    tholdmZS = "3.5",
    outfence = TRUE,
    norm = FALSE,
    outind = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mOUT requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mOUTOptions$new(
        vars = vars,
        group = group,
        boxpl = boxpl,
        outlcheck = outlcheck,
        fence = fence,
        tholdZS = tholdZS,
        tholdmZS = tholdmZS,
        outfence = outfence,
        norm = norm,
        outind = outind)

    analysis <- mOUTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

