
# This file is automatically generated, you probably don't want to edit this

mPCAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPCAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            selgroup = NULL,
            classVar = NULL,
            npc = 2,
            pcX = 1,
            pcY = 2,
            kMeansK = 2,
            regKFold = 5,
            screePlot = TRUE,
            loadingsTable = TRUE,
            loadingsHeatmap = TRUE,
            scorePlot = TRUE,
            biplot = TRUE,
            cos2Table = TRUE,
            cos2Heatmap = TRUE,
            kmeansTable = TRUE,
            regTable = TRUE,
            rocPlot = TRUE,
            roc_x = "1spec",
            roc_unit = "percent",
            palBrewer = "Dark2", ...) {

            super$initialize(
                package="jYS",
                name="mPCA",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..selgroup <- jmvcore::OptionLevel$new(
                "selgroup",
                selgroup,
                variable="(group)")
            private$..classVar <- jmvcore::OptionVariable$new(
                "classVar",
                classVar,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..npc <- jmvcore::OptionNumber$new(
                "npc",
                npc,
                min=1,
                default=2)
            private$..pcX <- jmvcore::OptionNumber$new(
                "pcX",
                pcX,
                min=1,
                default=1)
            private$..pcY <- jmvcore::OptionNumber$new(
                "pcY",
                pcY,
                min=1,
                default=2)
            private$..kMeansK <- jmvcore::OptionNumber$new(
                "kMeansK",
                kMeansK,
                min=2,
                default=2)
            private$..regKFold <- jmvcore::OptionNumber$new(
                "regKFold",
                regKFold,
                min=2,
                max=20,
                default=5)
            private$..screePlot <- jmvcore::OptionBool$new(
                "screePlot",
                screePlot,
                default=TRUE)
            private$..loadingsTable <- jmvcore::OptionBool$new(
                "loadingsTable",
                loadingsTable,
                default=TRUE)
            private$..loadingsHeatmap <- jmvcore::OptionBool$new(
                "loadingsHeatmap",
                loadingsHeatmap,
                default=TRUE)
            private$..scorePlot <- jmvcore::OptionBool$new(
                "scorePlot",
                scorePlot,
                default=TRUE)
            private$..biplot <- jmvcore::OptionBool$new(
                "biplot",
                biplot,
                default=TRUE)
            private$..cos2Table <- jmvcore::OptionBool$new(
                "cos2Table",
                cos2Table,
                default=TRUE)
            private$..cos2Heatmap <- jmvcore::OptionBool$new(
                "cos2Heatmap",
                cos2Heatmap,
                default=TRUE)
            private$..kmeansTable <- jmvcore::OptionBool$new(
                "kmeansTable",
                kmeansTable,
                default=TRUE)
            private$..regTable <- jmvcore::OptionBool$new(
                "regTable",
                regTable,
                default=TRUE)
            private$..rocPlot <- jmvcore::OptionBool$new(
                "rocPlot",
                rocPlot,
                default=TRUE)
            private$..roc_x <- jmvcore::OptionList$new(
                "roc_x",
                roc_x,
                options=list(
                    "spec",
                    "1spec"),
                default="1spec")
            private$..roc_unit <- jmvcore::OptionList$new(
                "roc_unit",
                roc_unit,
                options=list(
                    "decimal",
                    "percent"),
                default="percent")
            private$..palBrewer <- jmvcore::OptionList$new(
                "palBrewer",
                palBrewer,
                options=list(
                    "none",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Dark2")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..selgroup)
            self$.addOption(private$..classVar)
            self$.addOption(private$..npc)
            self$.addOption(private$..pcX)
            self$.addOption(private$..pcY)
            self$.addOption(private$..kMeansK)
            self$.addOption(private$..regKFold)
            self$.addOption(private$..screePlot)
            self$.addOption(private$..loadingsTable)
            self$.addOption(private$..loadingsHeatmap)
            self$.addOption(private$..scorePlot)
            self$.addOption(private$..biplot)
            self$.addOption(private$..cos2Table)
            self$.addOption(private$..cos2Heatmap)
            self$.addOption(private$..kmeansTable)
            self$.addOption(private$..regTable)
            self$.addOption(private$..rocPlot)
            self$.addOption(private$..roc_x)
            self$.addOption(private$..roc_unit)
            self$.addOption(private$..palBrewer)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        selgroup = function() private$..selgroup$value,
        classVar = function() private$..classVar$value,
        npc = function() private$..npc$value,
        pcX = function() private$..pcX$value,
        pcY = function() private$..pcY$value,
        kMeansK = function() private$..kMeansK$value,
        regKFold = function() private$..regKFold$value,
        screePlot = function() private$..screePlot$value,
        loadingsTable = function() private$..loadingsTable$value,
        loadingsHeatmap = function() private$..loadingsHeatmap$value,
        scorePlot = function() private$..scorePlot$value,
        biplot = function() private$..biplot$value,
        cos2Table = function() private$..cos2Table$value,
        cos2Heatmap = function() private$..cos2Heatmap$value,
        kmeansTable = function() private$..kmeansTable$value,
        regTable = function() private$..regTable$value,
        rocPlot = function() private$..rocPlot$value,
        roc_x = function() private$..roc_x$value,
        roc_unit = function() private$..roc_unit$value,
        palBrewer = function() private$..palBrewer$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..selgroup = NA,
        ..classVar = NA,
        ..npc = NA,
        ..pcX = NA,
        ..pcY = NA,
        ..kMeansK = NA,
        ..regKFold = NA,
        ..screePlot = NA,
        ..loadingsTable = NA,
        ..loadingsHeatmap = NA,
        ..scorePlot = NA,
        ..biplot = NA,
        ..cos2Table = NA,
        ..cos2Heatmap = NA,
        ..kmeansTable = NA,
        ..regTable = NA,
        ..rocPlot = NA,
        ..roc_x = NA,
        ..roc_unit = NA,
        ..palBrewer = NA)
)

mPCAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPCAResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        varianceTable = function() private$.items[["varianceTable"]],
        loadingsTable = function() private$.items[["loadingsTable"]],
        loadingsHeatmap = function() private$.items[["loadingsHeatmap"]],
        screePlot = function() private$.items[["screePlot"]],
        scorePlot = function() private$.items[["scorePlot"]],
        biplot = function() private$.items[["biplot"]],
        cos2Table = function() private$.items[["cos2Table"]],
        cos2Heatmap = function() private$.items[["cos2Heatmap"]],
        kmeansTable = function() private$.items[["kmeansTable"]],
        regTable = function() private$.items[["regTable"]],
        rocPlot = function() private$.items[["rocPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PCA Submodule",
                refs=list(
                    "jys"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Info",
                clearWith=list(
                    "group",
                    "selgroup")))
            self$add(jmvcore::Table$new(
                options=options,
                name="varianceTable",
                title="Component Eigenvalues and Explained Variance",
                rows=0,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="variance", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="cumulative", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingsTable",
                title="Factor Loadings",
                visible="(loadingsTable)",
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "npc"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="loadingsHeatmap",
                title="Factor Loadings Heatmap",
                visible="(loadingsHeatmap)",
                width=500,
                height=500,
                renderFun=".loadingsHeatmap",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "npc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="screePlot",
                title="Scree Plot with Parallel Analysis",
                visible="(screePlot)",
                width=600,
                height=450,
                renderFun=".screePlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup")))
            self$add(jmvcore::Image$new(
                options=options,
                name="scorePlot",
                title="Object score distribution with 95% ellipses",
                visible="(scorePlot)",
                width=600,
                height=500,
                renderFun=".scorePlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "classVar",
                    "pcX",
                    "pcY")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biplot",
                title="Influence vectors (Biplot)",
                visible="(biplot)",
                width=600,
                height=600,
                renderFun=".biplot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "pcX",
                    "pcY")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cos2Table",
                title="Quality of representation (Cos\u00B2)",
                visible="(cos2Table)",
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "npc"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="cos2Heatmap",
                title="Quality of representation (Cos\u00B2) Heatmap",
                visible="(cos2Heatmap)",
                width=500,
                height=500,
                renderFun=".cos2Heatmap",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "npc")))
            self$add(jmvcore::Table$new(
                options=options,
                name="kmeansTable",
                title="K-Means \u00ABBlind\u00BB Clustering vs Real Groups",
                visible="(kmeansTable)",
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "classVar",
                    "kMeansK"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric / Cluster", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value / Match count", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="regTable",
                title="Regression Model Performance (K-fold Cross-Validation)",
                visible="(regTable)",
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "classVar",
                    "npc",
                    "regKFold"),
                columns=list(
                    list(
                        `name`="fold", 
                        `title`="Fold", 
                        `type`="text"),
                    list(
                        `name`="accuracy", 
                        `title`="Accuracy", 
                        `type`="number"),
                    list(
                        `name`="sensitivity", 
                        `title`="Sensitivity", 
                        `type`="number"),
                    list(
                        `name`="specificity", 
                        `title`="Specificity", 
                        `type`="number"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="rocPlot",
                title="Regression Model ROC Curve (Full Dataset)",
                visible="(rocPlot)",
                width=500,
                height=500,
                renderFun=".rocPlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "selgroup",
                    "classVar",
                    "npc",
                    "roc_x",
                    "roc_unit",
                    "palBrewer")))}))

mPCABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPCABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mPCA",
                version = c(1,0,0),
                options = options,
                results = mPCAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PCA Submodule
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param selgroup .
#' @param classVar .
#' @param npc .
#' @param pcX .
#' @param pcY .
#' @param kMeansK .
#' @param regKFold .
#' @param screePlot .
#' @param loadingsTable .
#' @param loadingsHeatmap .
#' @param scorePlot .
#' @param biplot .
#' @param cos2Table .
#' @param cos2Heatmap .
#' @param kmeansTable .
#' @param regTable .
#' @param rocPlot .
#' @param roc_x .
#' @param roc_unit .
#' @param palBrewer .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$varianceTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingsHeatmap} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$screePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$scorePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cos2Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cos2Heatmap} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$kmeansTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$regTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rocPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$varianceTable$asDF}
#'
#' \code{as.data.frame(results$varianceTable)}
#'
#' @export
mPCA <- function(
    data,
    vars,
    group,
    selgroup,
    classVar,
    npc = 2,
    pcX = 1,
    pcY = 2,
    kMeansK = 2,
    regKFold = 5,
    screePlot = TRUE,
    loadingsTable = TRUE,
    loadingsHeatmap = TRUE,
    scorePlot = TRUE,
    biplot = TRUE,
    cos2Table = TRUE,
    cos2Heatmap = TRUE,
    kmeansTable = TRUE,
    regTable = TRUE,
    rocPlot = TRUE,
    roc_x = "1spec",
    roc_unit = "percent",
    palBrewer = "Dark2") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mPCA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(classVar)) classVar <- jmvcore::resolveQuo(jmvcore::enquo(classVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(classVar), classVar, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in classVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mPCAOptions$new(
        vars = vars,
        group = group,
        selgroup = selgroup,
        classVar = classVar,
        npc = npc,
        pcX = pcX,
        pcY = pcY,
        kMeansK = kMeansK,
        regKFold = regKFold,
        screePlot = screePlot,
        loadingsTable = loadingsTable,
        loadingsHeatmap = loadingsHeatmap,
        scorePlot = scorePlot,
        biplot = biplot,
        cos2Table = cos2Table,
        cos2Heatmap = cos2Heatmap,
        kmeansTable = kmeansTable,
        regTable = regTable,
        rocPlot = rocPlot,
        roc_x = roc_x,
        roc_unit = roc_unit,
        palBrewer = palBrewer)

    analysis <- mPCAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

