
# This file is automatically generated, you probably don't want to edit this

mPWROptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPWROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calc = "n",
            design = "independent",
            es = 0.5,
            power = 0.8,
            n = 30,
            alt = "two.sided",
            alpha = 0.05,
            n_ratio = 1,
            var_ratio = 1,
            plot_err = FALSE,
            power_curve = FALSE,
            power_es_curve = FALSE,
            n_es_curve = FALSE,
            k_total = 2,
            k_tested = 2,
            base_prob = 0.15,
            r2_predictor = 0,
            df_chisq = 1,
            factor_levels = 3,
            k_covariates = 0,
            margin = 0,
            crt = FALSE,
            cluster_size = 10,
            icc = 0.05,
            power_es_alpha_curve = FALSE, ...) {

            super$initialize(
                package="jYS",
                name="mPWR",
                requiresData=FALSE,
                ...)

            private$..calc <- jmvcore::OptionList$new(
                "calc",
                calc,
                options=list(
                    "n",
                    "power",
                    "es"),
                default="n")
            private$..design <- jmvcore::OptionList$new(
                "design",
                design,
                options=list(
                    "independent",
                    "welch",
                    "independent_np",
                    "paired",
                    "paired_np",
                    "one.sample",
                    "one.sample_np",
                    "onecor",
                    "onecor_np",
                    "linear",
                    "logistic",
                    "chisq",
                    "anova",
                    "survival"),
                default="independent")
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0.01,
                default=0.5)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=30)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two.sided",
                    "one.sided",
                    "equivalent",
                    "non-inferior",
                    "superior"),
                default="two.sided")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..n_ratio <- jmvcore::OptionNumber$new(
                "n_ratio",
                n_ratio,
                min=0,
                default=1)
            private$..var_ratio <- jmvcore::OptionNumber$new(
                "var_ratio",
                var_ratio,
                min=0.01,
                default=1)
            private$..plot_err <- jmvcore::OptionBool$new(
                "plot_err",
                plot_err,
                default=FALSE)
            private$..power_curve <- jmvcore::OptionBool$new(
                "power_curve",
                power_curve,
                default=FALSE)
            private$..power_es_curve <- jmvcore::OptionBool$new(
                "power_es_curve",
                power_es_curve,
                default=FALSE)
            private$..n_es_curve <- jmvcore::OptionBool$new(
                "n_es_curve",
                n_es_curve,
                default=FALSE)
            private$..k_total <- jmvcore::OptionInteger$new(
                "k_total",
                k_total,
                min=1,
                default=2)
            private$..k_tested <- jmvcore::OptionInteger$new(
                "k_tested",
                k_tested,
                min=1,
                default=2)
            private$..base_prob <- jmvcore::OptionNumber$new(
                "base_prob",
                base_prob,
                min=0.001,
                max=0.999,
                default=0.15)
            private$..r2_predictor <- jmvcore::OptionNumber$new(
                "r2_predictor",
                r2_predictor,
                min=0,
                max=0.99,
                default=0)
            private$..df_chisq <- jmvcore::OptionInteger$new(
                "df_chisq",
                df_chisq,
                min=1,
                default=1)
            private$..factor_levels <- jmvcore::OptionInteger$new(
                "factor_levels",
                factor_levels,
                min=2,
                default=3)
            private$..k_covariates <- jmvcore::OptionInteger$new(
                "k_covariates",
                k_covariates,
                min=0,
                default=0)
            private$..margin <- jmvcore::OptionNumber$new(
                "margin",
                margin,
                default=0)
            private$..crt <- jmvcore::OptionBool$new(
                "crt",
                crt,
                default=FALSE)
            private$..cluster_size <- jmvcore::OptionInteger$new(
                "cluster_size",
                cluster_size,
                min=1,
                default=10)
            private$..icc <- jmvcore::OptionNumber$new(
                "icc",
                icc,
                min=0,
                max=1,
                default=0.05)
            private$..power_es_alpha_curve <- jmvcore::OptionBool$new(
                "power_es_alpha_curve",
                power_es_alpha_curve,
                default=FALSE)

            self$.addOption(private$..calc)
            self$.addOption(private$..design)
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..alt)
            self$.addOption(private$..alpha)
            self$.addOption(private$..n_ratio)
            self$.addOption(private$..var_ratio)
            self$.addOption(private$..plot_err)
            self$.addOption(private$..power_curve)
            self$.addOption(private$..power_es_curve)
            self$.addOption(private$..n_es_curve)
            self$.addOption(private$..k_total)
            self$.addOption(private$..k_tested)
            self$.addOption(private$..base_prob)
            self$.addOption(private$..r2_predictor)
            self$.addOption(private$..df_chisq)
            self$.addOption(private$..factor_levels)
            self$.addOption(private$..k_covariates)
            self$.addOption(private$..margin)
            self$.addOption(private$..crt)
            self$.addOption(private$..cluster_size)
            self$.addOption(private$..icc)
            self$.addOption(private$..power_es_alpha_curve)
        }),
    active = list(
        calc = function() private$..calc$value,
        design = function() private$..design$value,
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        alt = function() private$..alt$value,
        alpha = function() private$..alpha$value,
        n_ratio = function() private$..n_ratio$value,
        var_ratio = function() private$..var_ratio$value,
        plot_err = function() private$..plot_err$value,
        power_curve = function() private$..power_curve$value,
        power_es_curve = function() private$..power_es_curve$value,
        n_es_curve = function() private$..n_es_curve$value,
        k_total = function() private$..k_total$value,
        k_tested = function() private$..k_tested$value,
        base_prob = function() private$..base_prob$value,
        r2_predictor = function() private$..r2_predictor$value,
        df_chisq = function() private$..df_chisq$value,
        factor_levels = function() private$..factor_levels$value,
        k_covariates = function() private$..k_covariates$value,
        margin = function() private$..margin$value,
        crt = function() private$..crt$value,
        cluster_size = function() private$..cluster_size$value,
        icc = function() private$..icc$value,
        power_es_alpha_curve = function() private$..power_es_alpha_curve$value),
    private = list(
        ..calc = NA,
        ..design = NA,
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..alt = NA,
        ..alpha = NA,
        ..n_ratio = NA,
        ..var_ratio = NA,
        ..plot_err = NA,
        ..power_curve = NA,
        ..power_es_curve = NA,
        ..n_es_curve = NA,
        ..k_total = NA,
        ..k_tested = NA,
        ..base_prob = NA,
        ..r2_predictor = NA,
        ..df_chisq = NA,
        ..factor_levels = NA,
        ..k_covariates = NA,
        ..margin = NA,
        ..crt = NA,
        ..cluster_size = NA,
        ..icc = NA,
        ..power_es_alpha_curve = NA)
)

mPWRResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPWRResults",
    inherit = jmvcore::Group,
    active = list(
        powerTable = function() private$.items[["powerTable"]],
        plot = function() private$.items[["plot"]],
        powerCurve = function() private$.items[["powerCurve"]],
        powerEsCurve = function() private$.items[["powerEsCurve"]],
        nEsCurve = function() private$.items[["nEsCurve"]],
        powerEsAlphaCurve = function() private$.items[["powerEsAlphaCurve"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="A Priori Power Analysis",
                refs=list(
                    "jys",
                    "pwrss_pkg",
                    "bulus_2024",
                    "bulus_2023",
                    "chow_2018",
                    "cohen_1988",
                    "lakens_2017"))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerTable",
                title="A Priori Power Analysis Results",
                rows=1,
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc"),
                columns=list(
                    list(
                        `name`="n1", 
                        `title`="N1", 
                        `type`="integer"),
                    list(
                        `name`="n2", 
                        `title`="N2", 
                        `type`="integer"),
                    list(
                        `name`="k1", 
                        `title`="Clusters 1", 
                        `type`="integer", 
                        `visible`="(crt && (design:independent || design:welch || design:paired || design:one.sample))"),
                    list(
                        `name`="k2", 
                        `title`="Clusters 2", 
                        `type`="integer", 
                        `visible`="(crt && (design:independent || design:welch || design:paired || design:one.sample))"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number", 
                        `format`="pvalue"),
                    list(
                        `name`="es", 
                        `title`="Effect Size", 
                        `type`="number"),
                    list(
                        `name`="n1_user", 
                        `title`="N1", 
                        `type`="integer", 
                        `superTitle`="User Defined"),
                    list(
                        `name`="n2_user", 
                        `title`="N2", 
                        `type`="integer", 
                        `superTitle`="User Defined"),
                    list(
                        `name`="es_user", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `superTitle`="User Defined"),
                    list(
                        `name`="power_user", 
                        `title`="Power", 
                        `type`="number", 
                        `format`="pvalue", 
                        `superTitle`="User Defined"),
                    list(
                        `name`="alpha", 
                        `title`="\u03B1", 
                        `type`="number", 
                        `format`="pvalue", 
                        `superTitle`="User Defined"),
                    list(
                        `name`="alt", 
                        `title`="Alternative", 
                        `type`="text", 
                        `superTitle`="User Defined"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Type 1 and Type 2 Error Plots",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(plot_err)",
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurve",
                title="Power Curve",
                width=500,
                height=400,
                renderFun=".powerCurve",
                visible="(power_curve)",
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEsCurve",
                title="Power by Effect Size",
                width=500,
                height=400,
                renderFun=".powerEsCurve",
                visible="(power_es_curve)",
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="nEsCurve",
                title="N by Effect Size",
                width=500,
                height=400,
                renderFun=".nEsCurve",
                visible="(n_es_curve)",
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEsAlphaCurve",
                title="Power by Effect Size and Alpha",
                width=500,
                height=400,
                renderFun=".powerEsAlphaCurve",
                visible="(power_es_alpha_curve)",
                clearWith=list(
                    "calc",
                    "design",
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha",
                    "n_ratio",
                    "var_ratio",
                    "k_total",
                    "k_tested",
                    "base_prob",
                    "r2_predictor",
                    "df_chisq",
                    "factor_levels",
                    "k_covariates",
                    "margin",
                    "crt",
                    "cluster_size",
                    "icc")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log / Errors",
                visible=FALSE))}))

mPWRBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mPWRBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mPWR",
                version = c(1,0,15),
                options = options,
                results = mPWRResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' A Priori Power Analysis
#'
#' 
#' @param calc .
#' @param design .
#' @param es .
#' @param power .
#' @param n .
#' @param alt .
#' @param alpha .
#' @param n_ratio .
#' @param var_ratio .
#' @param plot_err .
#' @param power_curve .
#' @param power_es_curve .
#' @param n_es_curve .
#' @param k_total .
#' @param k_tested .
#' @param base_prob .
#' @param r2_predictor .
#' @param df_chisq .
#' @param factor_levels .
#' @param k_covariates .
#' @param margin .
#' @param crt .
#' @param cluster_size .
#' @param icc .
#' @param power_es_alpha_curve .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$powerTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEsCurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$nEsCurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEsAlphaCurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powerTable$asDF}
#'
#' \code{as.data.frame(results$powerTable)}
#'
#' @export
mPWR <- function(
    calc = "n",
    design = "independent",
    es = 0.5,
    power = 0.8,
    n = 30,
    alt = "two.sided",
    alpha = 0.05,
    n_ratio = 1,
    var_ratio = 1,
    plot_err = FALSE,
    power_curve = FALSE,
    power_es_curve = FALSE,
    n_es_curve = FALSE,
    k_total = 2,
    k_tested = 2,
    base_prob = 0.15,
    r2_predictor = 0,
    df_chisq = 1,
    factor_levels = 3,
    k_covariates = 0,
    margin = 0,
    crt = FALSE,
    cluster_size = 10,
    icc = 0.05,
    power_es_alpha_curve = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mPWR requires jmvcore to be installed (restart may be required)")


    options <- mPWROptions$new(
        calc = calc,
        design = design,
        es = es,
        power = power,
        n = n,
        alt = alt,
        alpha = alpha,
        n_ratio = n_ratio,
        var_ratio = var_ratio,
        plot_err = plot_err,
        power_curve = power_curve,
        power_es_curve = power_es_curve,
        n_es_curve = n_es_curve,
        k_total = k_total,
        k_tested = k_tested,
        base_prob = base_prob,
        r2_predictor = r2_predictor,
        df_chisq = df_chisq,
        factor_levels = factor_levels,
        k_covariates = k_covariates,
        margin = margin,
        crt = crt,
        cluster_size = cluster_size,
        icc = icc,
        power_es_alpha_curve = power_es_alpha_curve)

    analysis <- mPWRClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

