
# This file is automatically generated, you probably don't want to edit this

mRFOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mRFOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            ntree = 500,
            mtry_method = "auto",
            mtry_val = 3,
            nodesize = 1,
            maxdepth = 0,
            sample_fraction = 1,
            partition = "oob",
            val_split = 30,
            cv_folds = 5,
            show_imp = FALSE,
            imp_type = "permutation",
            show_oob_curve = FALSE,
            show_matrix = FALSE,
            show_roc = FALSE,
            show_roc_cut = TRUE,
            show_roc_table = FALSE,
            roc_x = "1spec",
            roc_unit = "percent",
            multiclass_roc_type = "combined",
            palBrewer = "Dark2",
            show_pdp = FALSE,
            pdp_n_vars = 4,
            seed = 42, ...) {

            super$initialize(
                package="jYS",
                name="mRF",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                required=TRUE)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..ntree <- jmvcore::OptionInteger$new(
                "ntree",
                ntree,
                min=10,
                max=10000,
                default=500)
            private$..mtry_method <- jmvcore::OptionList$new(
                "mtry_method",
                mtry_method,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..mtry_val <- jmvcore::OptionInteger$new(
                "mtry_val",
                mtry_val,
                min=1,
                default=3)
            private$..nodesize <- jmvcore::OptionInteger$new(
                "nodesize",
                nodesize,
                min=1,
                default=1)
            private$..maxdepth <- jmvcore::OptionInteger$new(
                "maxdepth",
                maxdepth,
                min=0,
                default=0)
            private$..sample_fraction <- jmvcore::OptionNumber$new(
                "sample_fraction",
                sample_fraction,
                min=0.1,
                max=1,
                default=1)
            private$..partition <- jmvcore::OptionList$new(
                "partition",
                partition,
                options=list(
                    "oob",
                    "holdout",
                    "kfold"),
                default="oob")
            private$..val_split <- jmvcore::OptionNumber$new(
                "val_split",
                val_split,
                min=10,
                max=90,
                default=30)
            private$..cv_folds <- jmvcore::OptionInteger$new(
                "cv_folds",
                cv_folds,
                min=2,
                max=20,
                default=5)
            private$..show_imp <- jmvcore::OptionBool$new(
                "show_imp",
                show_imp,
                default=FALSE)
            private$..imp_type <- jmvcore::OptionList$new(
                "imp_type",
                imp_type,
                options=list(
                    "permutation",
                    "impurity"),
                default="permutation")
            private$..show_oob_curve <- jmvcore::OptionBool$new(
                "show_oob_curve",
                show_oob_curve,
                default=FALSE)
            private$..show_matrix <- jmvcore::OptionBool$new(
                "show_matrix",
                show_matrix,
                default=FALSE)
            private$..show_roc <- jmvcore::OptionBool$new(
                "show_roc",
                show_roc,
                default=FALSE)
            private$..show_roc_cut <- jmvcore::OptionBool$new(
                "show_roc_cut",
                show_roc_cut,
                default=TRUE)
            private$..show_roc_table <- jmvcore::OptionBool$new(
                "show_roc_table",
                show_roc_table,
                default=FALSE)
            private$..roc_x <- jmvcore::OptionList$new(
                "roc_x",
                roc_x,
                options=list(
                    "spec",
                    "1spec"),
                default="1spec")
            private$..roc_unit <- jmvcore::OptionList$new(
                "roc_unit",
                roc_unit,
                options=list(
                    "decimal",
                    "percent"),
                default="percent")
            private$..multiclass_roc_type <- jmvcore::OptionList$new(
                "multiclass_roc_type",
                multiclass_roc_type,
                options=list(
                    "combined",
                    "separate"),
                default="combined")
            private$..palBrewer <- jmvcore::OptionList$new(
                "palBrewer",
                palBrewer,
                options=list(
                    "none",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Dark2")
            private$..show_pdp <- jmvcore::OptionBool$new(
                "show_pdp",
                show_pdp,
                default=FALSE)
            private$..pdp_n_vars <- jmvcore::OptionInteger$new(
                "pdp_n_vars",
                pdp_n_vars,
                min=1,
                max=10,
                default=4)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..predClass <- jmvcore::OptionOutput$new(
                "predClass")
            private$..predProb <- jmvcore::OptionOutput$new(
                "predProb")

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..ntree)
            self$.addOption(private$..mtry_method)
            self$.addOption(private$..mtry_val)
            self$.addOption(private$..nodesize)
            self$.addOption(private$..maxdepth)
            self$.addOption(private$..sample_fraction)
            self$.addOption(private$..partition)
            self$.addOption(private$..val_split)
            self$.addOption(private$..cv_folds)
            self$.addOption(private$..show_imp)
            self$.addOption(private$..imp_type)
            self$.addOption(private$..show_oob_curve)
            self$.addOption(private$..show_matrix)
            self$.addOption(private$..show_roc)
            self$.addOption(private$..show_roc_cut)
            self$.addOption(private$..show_roc_table)
            self$.addOption(private$..roc_x)
            self$.addOption(private$..roc_unit)
            self$.addOption(private$..multiclass_roc_type)
            self$.addOption(private$..palBrewer)
            self$.addOption(private$..show_pdp)
            self$.addOption(private$..pdp_n_vars)
            self$.addOption(private$..seed)
            self$.addOption(private$..predClass)
            self$.addOption(private$..predProb)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        ntree = function() private$..ntree$value,
        mtry_method = function() private$..mtry_method$value,
        mtry_val = function() private$..mtry_val$value,
        nodesize = function() private$..nodesize$value,
        maxdepth = function() private$..maxdepth$value,
        sample_fraction = function() private$..sample_fraction$value,
        partition = function() private$..partition$value,
        val_split = function() private$..val_split$value,
        cv_folds = function() private$..cv_folds$value,
        show_imp = function() private$..show_imp$value,
        imp_type = function() private$..imp_type$value,
        show_oob_curve = function() private$..show_oob_curve$value,
        show_matrix = function() private$..show_matrix$value,
        show_roc = function() private$..show_roc$value,
        show_roc_cut = function() private$..show_roc_cut$value,
        show_roc_table = function() private$..show_roc_table$value,
        roc_x = function() private$..roc_x$value,
        roc_unit = function() private$..roc_unit$value,
        multiclass_roc_type = function() private$..multiclass_roc_type$value,
        palBrewer = function() private$..palBrewer$value,
        show_pdp = function() private$..show_pdp$value,
        pdp_n_vars = function() private$..pdp_n_vars$value,
        seed = function() private$..seed$value,
        predClass = function() private$..predClass$value,
        predProb = function() private$..predProb$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..ntree = NA,
        ..mtry_method = NA,
        ..mtry_val = NA,
        ..nodesize = NA,
        ..maxdepth = NA,
        ..sample_fraction = NA,
        ..partition = NA,
        ..val_split = NA,
        ..cv_folds = NA,
        ..show_imp = NA,
        ..imp_type = NA,
        ..show_oob_curve = NA,
        ..show_matrix = NA,
        ..show_roc = NA,
        ..show_roc_cut = NA,
        ..show_roc_table = NA,
        ..roc_x = NA,
        ..roc_unit = NA,
        ..multiclass_roc_type = NA,
        ..palBrewer = NA,
        ..show_pdp = NA,
        ..pdp_n_vars = NA,
        ..seed = NA,
        ..predClass = NA,
        ..predProb = NA)
)

mRFResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mRFResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        infoTable = function() private$.items[["infoTable"]],
        importanceTable = function() private$.items[["importanceTable"]],
        importancePlot = function() private$.items[["importancePlot"]],
        oobCurvePlot = function() private$.items[["oobCurvePlot"]],
        matrixTable = function() private$.items[["matrixTable"]],
        statsTable = function() private$.items[["statsTable"]],
        rocTable = function() private$.items[["rocTable"]],
        rocPlot = function() private$.items[["rocPlot"]],
        pdpPlot = function() private$.items[["pdpPlot"]],
        predClass = function() private$.items[["predClass"]],
        predProb = function() private$.items[["predProb"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Random Forest Classifier",
                refs=list(
                    "jys",
                    "rg",
                    "roc",
                    "breiman2001"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Conditions",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="infoTable",
                title="Model Information & Accuracy",
                rows=7,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "seed"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="importanceTable",
                title="Variable Importance",
                visible="(show_imp)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "imp_type",
                    "seed"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="imp", 
                        `title`="Importance", 
                        `type`="number"),
                    list(
                        `name`="rank", 
                        `title`="Rank", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="importancePlot",
                title="Variable Importance Chart",
                visible="(show_imp)",
                width=550,
                height=400,
                renderFun=".importancePlot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "imp_type",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="oobCurvePlot",
                title="OOB Error Convergence",
                visible="(show_oob_curve)",
                width=550,
                height=350,
                renderFun=".oobCurvePlot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "seed")))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrixTable",
                title="Confusion Matrix",
                visible="(show_matrix)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "seed"),
                columns=list(
                    list(
                        `name`="actual", 
                        `title`="Actual Class", 
                        `type`="text"),
                    list(
                        `name`="predicted", 
                        `title`="Predicted Class", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="statsTable",
                title="Performance Statistics",
                visible="(show_matrix)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "seed"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="trainVal", 
                        `title`="Training", 
                        `type`="number"),
                    list(
                        `name`="cvVal", 
                        `title`="Validation", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rocTable",
                title="ROC Quantitative Evaluation",
                visible="(show_roc && show_roc_table)",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "roc_x",
                    "roc_unit",
                    "multiclass_roc_type",
                    "palBrewer",
                    "show_roc_cut",
                    "show_roc_table",
                    "seed"),
                columns=list(
                    list(
                        `name`="part", 
                        `title`="Curve", 
                        `type`="text"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number"),
                    list(
                        `name`="cutoff", 
                        `title`="Cut-off", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Sensitivity (Se)", 
                        `type`="number"),
                    list(
                        `name`="sp", 
                        `title`="Specificity (Sp)", 
                        `type`="number"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="rocPlot",
                title="ROC Analysis Comparison",
                visible="(show_roc)",
                template=jmvcore::Image$new(
                    options=options,
                    width=500,
                    height=500,
                    renderFun=".rocPlot",
                    requiresData=TRUE),
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "roc_x",
                    "roc_unit",
                    "multiclass_roc_type",
                    "palBrewer",
                    "show_roc_cut",
                    "show_roc_table",
                    "seed")))
            self$add(jmvcore::Array$new(
                options=options,
                name="pdpPlot",
                title="Partial Dependence Plots",
                visible="(show_pdp)",
                template=jmvcore::Image$new(
                    options=options,
                    width=550,
                    height=400,
                    renderFun=".pdpPlot",
                    requiresData=TRUE),
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "pdp_n_vars",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predClass",
                title="Predicted Class",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predProb",
                title="Predicted Probability",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "ntree",
                    "mtry_method",
                    "mtry_val",
                    "nodesize",
                    "maxdepth",
                    "sample_fraction",
                    "partition",
                    "val_split",
                    "cv_folds",
                    "seed")))}))

mRFBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mRFBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mRF",
                version = c(1,0,0),
                options = options,
                results = mRFResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Random Forest Classifier
#'
#' Random Forest Classifier using the ranger package. Note that data 
#' partitioning uses a hardcoded random seed (42) for reproducibility.
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param ntree .
#' @param mtry_method .
#' @param mtry_val .
#' @param nodesize .
#' @param maxdepth .
#' @param sample_fraction .
#' @param partition .
#' @param val_split .
#' @param cv_folds .
#' @param show_imp .
#' @param imp_type .
#' @param show_oob_curve .
#' @param show_matrix .
#' @param show_roc .
#' @param show_roc_cut .
#' @param show_roc_table .
#' @param roc_x .
#' @param roc_unit .
#' @param multiclass_roc_type .
#' @param palBrewer .
#' @param show_pdp .
#' @param pdp_n_vars .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$importanceTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$importancePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$oobCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$matrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$statsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rocPlot} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$pdpPlot} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$predClass} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predProb} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infoTable$asDF}
#'
#' \code{as.data.frame(results$infoTable)}
#'
#' @export
mRF <- function(
    data,
    dep,
    covs,
    factors,
    ntree = 500,
    mtry_method = "auto",
    mtry_val = 3,
    nodesize = 1,
    maxdepth = 0,
    sample_fraction = 1,
    partition = "oob",
    val_split = 30,
    cv_folds = 5,
    show_imp = FALSE,
    imp_type = "permutation",
    show_oob_curve = FALSE,
    show_matrix = FALSE,
    show_roc = FALSE,
    show_roc_cut = TRUE,
    show_roc_table = FALSE,
    roc_x = "1spec",
    roc_unit = "percent",
    multiclass_roc_type = "combined",
    palBrewer = "Dark2",
    show_pdp = FALSE,
    pdp_n_vars = 4,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mRF requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mRFOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        ntree = ntree,
        mtry_method = mtry_method,
        mtry_val = mtry_val,
        nodesize = nodesize,
        maxdepth = maxdepth,
        sample_fraction = sample_fraction,
        partition = partition,
        val_split = val_split,
        cv_folds = cv_folds,
        show_imp = show_imp,
        imp_type = imp_type,
        show_oob_curve = show_oob_curve,
        show_matrix = show_matrix,
        show_roc = show_roc,
        show_roc_cut = show_roc_cut,
        show_roc_table = show_roc_table,
        roc_x = roc_x,
        roc_unit = roc_unit,
        multiclass_roc_type = multiclass_roc_type,
        palBrewer = palBrewer,
        show_pdp = show_pdp,
        pdp_n_vars = pdp_n_vars,
        seed = seed)

    analysis <- mRFClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

