
# This file is automatically generated, you probably don't want to edit this

mROCOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mROCOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            class = NULL,
            groups = NULL,
            selgroup = NULL,
            theBest = "bssY",
            cmpDeLong = "none",
            mAst = FALSE,
            ciAUC = FALSE,
            ciWidth = 95,
            perc = TRUE,
            ciMark = FALSE,
            direction = TRUE,
            lwd = 3,
            dotline = FALSE,
            BW = FALSE,
            legacy = FALSE,
            polygon = FALSE,
            legBox = FALSE,
            sepROC = FALSE,
            splitROC = FALSE,
            palBrewer = "Dark2", ...) {

            super$initialize(
                package="jYS",
                name="mROC",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..class <- jmvcore::OptionVariable$new(
                "class",
                class,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..groups <- jmvcore::OptionVariable$new(
                "groups",
                groups,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..selgroup <- jmvcore::OptionLevel$new(
                "selgroup",
                selgroup,
                variable="(groups)")
            private$..theBest <- jmvcore::OptionList$new(
                "theBest",
                theBest,
                options=list(
                    "none",
                    "bestY",
                    "bssY",
                    "bestC",
                    "bssC"),
                default="bssY")
            private$..cmpDeLong <- jmvcore::OptionList$new(
                "cmpDeLong",
                cmpDeLong,
                options=list(
                    "none",
                    "succ",
                    "wcontr"),
                default="none")
            private$..mAst <- jmvcore::OptionBool$new(
                "mAst",
                mAst,
                default=FALSE)
            private$..ciAUC <- jmvcore::OptionBool$new(
                "ciAUC",
                ciAUC,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..perc <- jmvcore::OptionBool$new(
                "perc",
                perc,
                default=TRUE)
            private$..ciMark <- jmvcore::OptionBool$new(
                "ciMark",
                ciMark,
                default=FALSE)
            private$..direction <- jmvcore::OptionBool$new(
                "direction",
                direction,
                default=TRUE)
            private$..lwd <- jmvcore::OptionNumber$new(
                "lwd",
                lwd,
                min=1,
                max=8,
                default=3)
            private$..dotline <- jmvcore::OptionBool$new(
                "dotline",
                dotline,
                default=FALSE)
            private$..BW <- jmvcore::OptionBool$new(
                "BW",
                BW,
                default=FALSE)
            private$..legacy <- jmvcore::OptionBool$new(
                "legacy",
                legacy,
                default=FALSE)
            private$..polygon <- jmvcore::OptionBool$new(
                "polygon",
                polygon,
                default=FALSE)
            private$..legBox <- jmvcore::OptionBool$new(
                "legBox",
                legBox,
                default=FALSE)
            private$..sepROC <- jmvcore::OptionBool$new(
                "sepROC",
                sepROC,
                default=FALSE)
            private$..splitROC <- jmvcore::OptionBool$new(
                "splitROC",
                splitROC,
                default=FALSE)
            private$..palBrewer <- jmvcore::OptionList$new(
                "palBrewer",
                palBrewer,
                options=list(
                    "none",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Dark2")

            self$.addOption(private$..vars)
            self$.addOption(private$..class)
            self$.addOption(private$..groups)
            self$.addOption(private$..selgroup)
            self$.addOption(private$..theBest)
            self$.addOption(private$..cmpDeLong)
            self$.addOption(private$..mAst)
            self$.addOption(private$..ciAUC)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..perc)
            self$.addOption(private$..ciMark)
            self$.addOption(private$..direction)
            self$.addOption(private$..lwd)
            self$.addOption(private$..dotline)
            self$.addOption(private$..BW)
            self$.addOption(private$..legacy)
            self$.addOption(private$..polygon)
            self$.addOption(private$..legBox)
            self$.addOption(private$..sepROC)
            self$.addOption(private$..splitROC)
            self$.addOption(private$..palBrewer)
        }),
    active = list(
        vars = function() private$..vars$value,
        class = function() private$..class$value,
        groups = function() private$..groups$value,
        selgroup = function() private$..selgroup$value,
        theBest = function() private$..theBest$value,
        cmpDeLong = function() private$..cmpDeLong$value,
        mAst = function() private$..mAst$value,
        ciAUC = function() private$..ciAUC$value,
        ciWidth = function() private$..ciWidth$value,
        perc = function() private$..perc$value,
        ciMark = function() private$..ciMark$value,
        direction = function() private$..direction$value,
        lwd = function() private$..lwd$value,
        dotline = function() private$..dotline$value,
        BW = function() private$..BW$value,
        legacy = function() private$..legacy$value,
        polygon = function() private$..polygon$value,
        legBox = function() private$..legBox$value,
        sepROC = function() private$..sepROC$value,
        splitROC = function() private$..splitROC$value,
        palBrewer = function() private$..palBrewer$value),
    private = list(
        ..vars = NA,
        ..class = NA,
        ..groups = NA,
        ..selgroup = NA,
        ..theBest = NA,
        ..cmpDeLong = NA,
        ..mAst = NA,
        ..ciAUC = NA,
        ..ciWidth = NA,
        ..perc = NA,
        ..ciMark = NA,
        ..direction = NA,
        ..lwd = NA,
        ..dotline = NA,
        ..BW = NA,
        ..legacy = NA,
        ..polygon = NA,
        ..legBox = NA,
        ..sepROC = NA,
        ..splitROC = NA,
        ..palBrewer = NA)
)

mROCResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mROCResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        plots = function() private$.items[["plots"]],
        splots = function() private$.items[["splots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ROC classification",
                refs=list(
                    "jys",
                    "roc"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Conditions",
                clearWith=list(
                    "groups")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="ROC by predictors",
                width=500,
                height=500,
                renderFun=".plot",
                requiresData=TRUE))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="ROC by groups",
                visible="(sepROC)",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plot",
                    requiresData=TRUE)))
            self$add(jmvcore::Array$new(
                options=options,
                name="splots",
                title="Splitted ROC by predictors",
                visible="(splitROC)",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plot",
                    requiresData=TRUE)))}))

mROCBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mROCBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mROC",
                version = c(1,0,11),
                options = options,
                results = mROCResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ROC classification
#'
#' 
#' @param data .
#' @param vars .
#' @param class .
#' @param groups .
#' @param selgroup .
#' @param theBest .
#' @param cmpDeLong .
#' @param mAst .
#' @param ciAUC .
#' @param ciWidth .
#' @param perc .
#' @param ciMark .
#' @param direction .
#' @param lwd .
#' @param dotline .
#' @param BW .
#' @param legacy .
#' @param polygon .
#' @param legBox .
#' @param sepROC .
#' @param splitROC .
#' @param palBrewer .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$splots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
mROC <- function(
    data,
    vars,
    class,
    groups,
    selgroup,
    theBest = "bssY",
    cmpDeLong = "none",
    mAst = FALSE,
    ciAUC = FALSE,
    ciWidth = 95,
    perc = TRUE,
    ciMark = FALSE,
    direction = TRUE,
    lwd = 3,
    dotline = FALSE,
    BW = FALSE,
    legacy = FALSE,
    polygon = FALSE,
    legBox = FALSE,
    sepROC = FALSE,
    splitROC = FALSE,
    palBrewer = "Dark2") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mROC requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(class)) class <- jmvcore::resolveQuo(jmvcore::enquo(class))
    if ( ! missing(groups)) groups <- jmvcore::resolveQuo(jmvcore::enquo(groups))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(class), class, NULL),
            `if`( ! missing(groups), groups, NULL))

    for (v in class) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groups) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mROCOptions$new(
        vars = vars,
        class = class,
        groups = groups,
        selgroup = selgroup,
        theBest = theBest,
        cmpDeLong = cmpDeLong,
        mAst = mAst,
        ciAUC = ciAUC,
        ciWidth = ciWidth,
        perc = perc,
        ciMark = ciMark,
        direction = direction,
        lwd = lwd,
        dotline = dotline,
        BW = BW,
        legacy = legacy,
        polygon = polygon,
        legBox = legBox,
        sepROC = sepROC,
        splitROC = splitROC,
        palBrewer = palBrewer)

    analysis <- mROCClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

