
# This file is automatically generated, you probably don't want to edit this

mSNPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mSNPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            outcome = NULL,
            covs = NULL,
            freqTable = TRUE,
            freqPct = FALSE,
            groupTable = TRUE,
            groupAlleles = TRUE,
            polyDf1 = FALSE,
            groupTotal = FALSE,
            hwTests = TRUE,
            alpha = "0.05",
            hwPerm = FALSE,
            nPerm = 1000,
            ternaryPlot = FALSE,
            ternaryRegion = "1",
            ternaryShowMAF = FALSE,
            qqPlot = FALSE,
            barPlot = FALSE,
            hweSplitOutcome = FALSE,
            gender = NULL,
            xLinked = FALSE,
            assocEnable = FALSE,
            geneticModel = "all",
            assocForest = FALSE,
            assocForestTrunc = TRUE,
            manhattanPlot = FALSE,
            popMetrics = FALSE,
            mafThreshold = "none",
            mdrEnable = FALSE,
            mdrOrder = "2",
            mdrFolds = "10",
            mdrPermTest = FALSE,
            nPermMDR = 100,
            mdrSeed = 42,
            mdrCellTable = FALSE,
            mdrHeatmap = FALSE,
            mdrBarPlot = FALSE,
            ldEnable = FALSE,
            ldTable = TRUE,
            ldHeatmap = FALSE,
            ldMetric = "r2",
            adjust = "none",
            qcCallRate = "none",
            qcMaf = "none",
            qcHwe = "none", ...) {

            super$initialize(
                package="jYS",
                name="mSNP",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                required=FALSE,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..freqTable <- jmvcore::OptionBool$new(
                "freqTable",
                freqTable,
                default=TRUE)
            private$..freqPct <- jmvcore::OptionBool$new(
                "freqPct",
                freqPct,
                default=FALSE)
            private$..groupTable <- jmvcore::OptionBool$new(
                "groupTable",
                groupTable,
                default=TRUE)
            private$..groupAlleles <- jmvcore::OptionBool$new(
                "groupAlleles",
                groupAlleles,
                default=TRUE)
            private$..polyDf1 <- jmvcore::OptionBool$new(
                "polyDf1",
                polyDf1,
                default=FALSE)
            private$..groupTotal <- jmvcore::OptionBool$new(
                "groupTotal",
                groupTotal,
                default=FALSE)
            private$..hwTests <- jmvcore::OptionBool$new(
                "hwTests",
                hwTests,
                default=TRUE)
            private$..alpha <- jmvcore::OptionList$new(
                "alpha",
                alpha,
                options=list(
                    "0.05",
                    "0.01",
                    "0.001",
                    "0.10"),
                default="0.05")
            private$..hwPerm <- jmvcore::OptionBool$new(
                "hwPerm",
                hwPerm,
                default=FALSE)
            private$..nPerm <- jmvcore::OptionNumber$new(
                "nPerm",
                nPerm,
                default=1000)
            private$..ternaryPlot <- jmvcore::OptionBool$new(
                "ternaryPlot",
                ternaryPlot,
                default=FALSE)
            private$..ternaryRegion <- jmvcore::OptionList$new(
                "ternaryRegion",
                ternaryRegion,
                options=list(
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7"),
                default="1")
            private$..ternaryShowMAF <- jmvcore::OptionBool$new(
                "ternaryShowMAF",
                ternaryShowMAF,
                default=FALSE)
            private$..qqPlot <- jmvcore::OptionBool$new(
                "qqPlot",
                qqPlot,
                default=FALSE)
            private$..barPlot <- jmvcore::OptionBool$new(
                "barPlot",
                barPlot,
                default=FALSE)
            private$..hweSplitOutcome <- jmvcore::OptionBool$new(
                "hweSplitOutcome",
                hweSplitOutcome,
                default=FALSE)
            private$..gender <- jmvcore::OptionVariable$new(
                "gender",
                gender,
                required=FALSE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..xLinked <- jmvcore::OptionBool$new(
                "xLinked",
                xLinked,
                default=FALSE)
            private$..assocEnable <- jmvcore::OptionBool$new(
                "assocEnable",
                assocEnable,
                default=FALSE)
            private$..geneticModel <- jmvcore::OptionList$new(
                "geneticModel",
                geneticModel,
                options=list(
                    "all",
                    "codominant",
                    "dominant",
                    "recessive",
                    "overdominant",
                    "log-additive"),
                default="all")
            private$..assocForest <- jmvcore::OptionBool$new(
                "assocForest",
                assocForest,
                default=FALSE)
            private$..assocForestTrunc <- jmvcore::OptionBool$new(
                "assocForestTrunc",
                assocForestTrunc,
                default=TRUE)
            private$..manhattanPlot <- jmvcore::OptionBool$new(
                "manhattanPlot",
                manhattanPlot,
                default=FALSE)
            private$..popMetrics <- jmvcore::OptionBool$new(
                "popMetrics",
                popMetrics,
                default=FALSE)
            private$..mafThreshold <- jmvcore::OptionList$new(
                "mafThreshold",
                mafThreshold,
                options=list(
                    "none",
                    "0.01",
                    "0.05",
                    "0.10"),
                default="none")
            private$..mdrEnable <- jmvcore::OptionBool$new(
                "mdrEnable",
                mdrEnable,
                default=FALSE)
            private$..mdrOrder <- jmvcore::OptionList$new(
                "mdrOrder",
                mdrOrder,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="2")
            private$..mdrFolds <- jmvcore::OptionList$new(
                "mdrFolds",
                mdrFolds,
                options=list(
                    "3",
                    "5",
                    "10"),
                default="10")
            private$..mdrPermTest <- jmvcore::OptionBool$new(
                "mdrPermTest",
                mdrPermTest,
                default=FALSE)
            private$..nPermMDR <- jmvcore::OptionNumber$new(
                "nPermMDR",
                nPermMDR,
                default=100)
            private$..mdrSeed <- jmvcore::OptionNumber$new(
                "mdrSeed",
                mdrSeed,
                default=42)
            private$..mdrCellTable <- jmvcore::OptionBool$new(
                "mdrCellTable",
                mdrCellTable,
                default=FALSE)
            private$..mdrHeatmap <- jmvcore::OptionBool$new(
                "mdrHeatmap",
                mdrHeatmap,
                default=FALSE)
            private$..mdrBarPlot <- jmvcore::OptionBool$new(
                "mdrBarPlot",
                mdrBarPlot,
                default=FALSE)
            private$..ldEnable <- jmvcore::OptionBool$new(
                "ldEnable",
                ldEnable,
                default=FALSE)
            private$..ldTable <- jmvcore::OptionBool$new(
                "ldTable",
                ldTable,
                default=TRUE)
            private$..ldHeatmap <- jmvcore::OptionBool$new(
                "ldHeatmap",
                ldHeatmap,
                default=FALSE)
            private$..ldMetric <- jmvcore::OptionList$new(
                "ldMetric",
                ldMetric,
                options=list(
                    "r2",
                    "Dprime"),
                default="r2")
            private$..adjust <- jmvcore::OptionList$new(
                "adjust",
                adjust,
                options=list(
                    "none",
                    "bonferroni",
                    "holm",
                    "fdr"),
                default="none")
            private$..qcCallRate <- jmvcore::OptionList$new(
                "qcCallRate",
                qcCallRate,
                options=list(
                    "none",
                    "0.90",
                    "0.95",
                    "0.98"),
                default="none")
            private$..qcMaf <- jmvcore::OptionList$new(
                "qcMaf",
                qcMaf,
                options=list(
                    "none",
                    "0.01",
                    "0.05",
                    "0.10"),
                default="none")
            private$..qcHwe <- jmvcore::OptionList$new(
                "qcHwe",
                qcHwe,
                options=list(
                    "none",
                    "0.05",
                    "0.01",
                    "0.001",
                    "0.0001"),
                default="none")
            private$..prsOutput <- jmvcore::OptionOutput$new(
                "prsOutput")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..outcome)
            self$.addOption(private$..covs)
            self$.addOption(private$..freqTable)
            self$.addOption(private$..freqPct)
            self$.addOption(private$..groupTable)
            self$.addOption(private$..groupAlleles)
            self$.addOption(private$..polyDf1)
            self$.addOption(private$..groupTotal)
            self$.addOption(private$..hwTests)
            self$.addOption(private$..alpha)
            self$.addOption(private$..hwPerm)
            self$.addOption(private$..nPerm)
            self$.addOption(private$..ternaryPlot)
            self$.addOption(private$..ternaryRegion)
            self$.addOption(private$..ternaryShowMAF)
            self$.addOption(private$..qqPlot)
            self$.addOption(private$..barPlot)
            self$.addOption(private$..hweSplitOutcome)
            self$.addOption(private$..gender)
            self$.addOption(private$..xLinked)
            self$.addOption(private$..assocEnable)
            self$.addOption(private$..geneticModel)
            self$.addOption(private$..assocForest)
            self$.addOption(private$..assocForestTrunc)
            self$.addOption(private$..manhattanPlot)
            self$.addOption(private$..popMetrics)
            self$.addOption(private$..mafThreshold)
            self$.addOption(private$..mdrEnable)
            self$.addOption(private$..mdrOrder)
            self$.addOption(private$..mdrFolds)
            self$.addOption(private$..mdrPermTest)
            self$.addOption(private$..nPermMDR)
            self$.addOption(private$..mdrSeed)
            self$.addOption(private$..mdrCellTable)
            self$.addOption(private$..mdrHeatmap)
            self$.addOption(private$..mdrBarPlot)
            self$.addOption(private$..ldEnable)
            self$.addOption(private$..ldTable)
            self$.addOption(private$..ldHeatmap)
            self$.addOption(private$..ldMetric)
            self$.addOption(private$..adjust)
            self$.addOption(private$..qcCallRate)
            self$.addOption(private$..qcMaf)
            self$.addOption(private$..qcHwe)
            self$.addOption(private$..prsOutput)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        outcome = function() private$..outcome$value,
        covs = function() private$..covs$value,
        freqTable = function() private$..freqTable$value,
        freqPct = function() private$..freqPct$value,
        groupTable = function() private$..groupTable$value,
        groupAlleles = function() private$..groupAlleles$value,
        polyDf1 = function() private$..polyDf1$value,
        groupTotal = function() private$..groupTotal$value,
        hwTests = function() private$..hwTests$value,
        alpha = function() private$..alpha$value,
        hwPerm = function() private$..hwPerm$value,
        nPerm = function() private$..nPerm$value,
        ternaryPlot = function() private$..ternaryPlot$value,
        ternaryRegion = function() private$..ternaryRegion$value,
        ternaryShowMAF = function() private$..ternaryShowMAF$value,
        qqPlot = function() private$..qqPlot$value,
        barPlot = function() private$..barPlot$value,
        hweSplitOutcome = function() private$..hweSplitOutcome$value,
        gender = function() private$..gender$value,
        xLinked = function() private$..xLinked$value,
        assocEnable = function() private$..assocEnable$value,
        geneticModel = function() private$..geneticModel$value,
        assocForest = function() private$..assocForest$value,
        assocForestTrunc = function() private$..assocForestTrunc$value,
        manhattanPlot = function() private$..manhattanPlot$value,
        popMetrics = function() private$..popMetrics$value,
        mafThreshold = function() private$..mafThreshold$value,
        mdrEnable = function() private$..mdrEnable$value,
        mdrOrder = function() private$..mdrOrder$value,
        mdrFolds = function() private$..mdrFolds$value,
        mdrPermTest = function() private$..mdrPermTest$value,
        nPermMDR = function() private$..nPermMDR$value,
        mdrSeed = function() private$..mdrSeed$value,
        mdrCellTable = function() private$..mdrCellTable$value,
        mdrHeatmap = function() private$..mdrHeatmap$value,
        mdrBarPlot = function() private$..mdrBarPlot$value,
        ldEnable = function() private$..ldEnable$value,
        ldTable = function() private$..ldTable$value,
        ldHeatmap = function() private$..ldHeatmap$value,
        ldMetric = function() private$..ldMetric$value,
        adjust = function() private$..adjust$value,
        qcCallRate = function() private$..qcCallRate$value,
        qcMaf = function() private$..qcMaf$value,
        qcHwe = function() private$..qcHwe$value,
        prsOutput = function() private$..prsOutput$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..outcome = NA,
        ..covs = NA,
        ..freqTable = NA,
        ..freqPct = NA,
        ..groupTable = NA,
        ..groupAlleles = NA,
        ..polyDf1 = NA,
        ..groupTotal = NA,
        ..hwTests = NA,
        ..alpha = NA,
        ..hwPerm = NA,
        ..nPerm = NA,
        ..ternaryPlot = NA,
        ..ternaryRegion = NA,
        ..ternaryShowMAF = NA,
        ..qqPlot = NA,
        ..barPlot = NA,
        ..hweSplitOutcome = NA,
        ..gender = NA,
        ..xLinked = NA,
        ..assocEnable = NA,
        ..geneticModel = NA,
        ..assocForest = NA,
        ..assocForestTrunc = NA,
        ..manhattanPlot = NA,
        ..popMetrics = NA,
        ..mafThreshold = NA,
        ..mdrEnable = NA,
        ..mdrOrder = NA,
        ..mdrFolds = NA,
        ..mdrPermTest = NA,
        ..nPermMDR = NA,
        ..mdrSeed = NA,
        ..mdrCellTable = NA,
        ..mdrHeatmap = NA,
        ..mdrBarPlot = NA,
        ..ldEnable = NA,
        ..ldTable = NA,
        ..ldHeatmap = NA,
        ..ldMetric = NA,
        ..adjust = NA,
        ..qcCallRate = NA,
        ..qcMaf = NA,
        ..qcHwe = NA,
        ..prsOutput = NA)
)

mSNPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mSNPResults",
    inherit = jmvcore::Group,
    active = list(
        hweGroup = function() private$.items[["hweGroup"]],
        assocGroup = function() private$.items[["assocGroup"]],
        qcGroup = function() private$.items[["qcGroup"]],
        popGroup = function() private$.items[["popGroup"]],
        mdrGroup = function() private$.items[["mdrGroup"]],
        ldGroup = function() private$.items[["ldGroup"]],
        prsOutput = function() private$.items[["prsOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single Nucleotide Polymorphism",
                refs=list(
                    "jys",
                    "hw_pkg",
                    "mdr_ritchie",
                    "mdr_hahn",
                    "botstein1980"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    freqTable = function() private$.items[["freqTable"]],
                    groupAnalysisTable = function() private$.items[["groupAnalysisTable"]],
                    hwTable = function() private$.items[["hwTable"]],
                    ternaryPlot = function() private$.items[["ternaryPlot"]],
                    qqPlot = function() private$.items[["qqPlot"]],
                    barPlot = function() private$.items[["barPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="hweGroup",
                            title="Hardy-Weinberg Equilibrium (HWE) Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="freqTable",
                            title="Genotype and Allele Frequencies",
                            visible="(freqTable)",
                            clearWith=list(
                                "vars",
                                "group",
                                "mafThreshold",
                                "freqPct",
                                "hweSplitOutcome",
                                "outcome",
                                "xLinked",
                                "gender",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Marker", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="group", 
                                    `title`="Population", 
                                    `type`="text", 
                                    `visible`="(group)"),
                                list(
                                    `name`="p_freq", 
                                    `title`="p (A)", 
                                    `type`="number"),
                                list(
                                    `name`="q_freq", 
                                    `title`="q (B)", 
                                    `type`="number"),
                                list(
                                    `name`="obsAA", 
                                    `title`="Obs AA", 
                                    `type`="text"),
                                list(
                                    `name`="obsAB", 
                                    `title`="Obs AB", 
                                    `type`="text"),
                                list(
                                    `name`="obsBB", 
                                    `title`="Obs BB", 
                                    `type`="text"),
                                list(
                                    `name`="expAA", 
                                    `title`="Exp AA", 
                                    `type`="text"),
                                list(
                                    `name`="expAB", 
                                    `title`="Exp AB", 
                                    `type`="text"),
                                list(
                                    `name`="expBB", 
                                    `title`="Exp BB", 
                                    `type`="text"),
                                list(
                                    `name`="h_obs", 
                                    `title`="H(obs)", 
                                    `type`="number"),
                                list(
                                    `name`="h_exp", 
                                    `title`="H(exp)", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="groupAnalysisTable",
                            title="Analysis of Alleles and Genotypes by Groups",
                            clearWith=list(
                                "vars",
                                "group",
                                "freqPct",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Polymorphism", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="genotype", 
                                    `title`="Genotype", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="hwTable",
                            title="Hardy-Weinberg Equilibrium Statistical Tests",
                            visible="(hwTests)",
                            clearWith=list(
                                "vars",
                                "group",
                                "hwPerm",
                                "nPerm",
                                "adjust",
                                "hweSplitOutcome",
                                "outcome",
                                "xLinked",
                                "gender",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Marker", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="group", 
                                    `title`="Population", 
                                    `type`="text", 
                                    `visible`="(group)"),
                                list(
                                    `name`="chi_stat", 
                                    `title`="\u03C7\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="chi_p", 
                                    `title`="Chi-square p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="chi_p_adj", 
                                    `title`="Chi-square p-adj", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="exact_p", 
                                    `title`="Exact p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="exact_p_adj", 
                                    `title`="Exact p-adj", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="lr_stat", 
                                    `title`="LRT Stat", 
                                    `type`="number"),
                                list(
                                    `name`="lr_p", 
                                    `title`="LRT p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="lr_p_adj", 
                                    `title`="LRT p-adj", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="perm_p", 
                                    `title`="Permutation p", 
                                    `type`="number", 
                                    `format`="zto,pvalue", 
                                    `visible`="(hwPerm)"),
                                list(
                                    `name`="perm_p_adj", 
                                    `title`="Permutation p-adj", 
                                    `type`="number", 
                                    `format`="zto,pvalue", 
                                    `visible`="(hwPerm)"),
                                list(
                                    `name`="fis", 
                                    `title`="F_IS", 
                                    `type`="number"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ternaryPlot",
                            title="Ternary diagram (de Finetti)",
                            width=600,
                            height=500,
                            renderFun=".plotTernary",
                            requiresData=TRUE,
                            visible="(ternaryPlot)",
                            clearWith=list(
                                "vars",
                                "group",
                                "ternaryRegion",
                                "ternaryShowMAF",
                                "mafThreshold",
                                "hweSplitOutcome",
                                "outcome",
                                "xLinked",
                                "gender",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="qqPlot",
                            title="Q-Q plot of HWE p-values",
                            width=550,
                            height=450,
                            renderFun=".plotQQ",
                            requiresData=TRUE,
                            visible="(qqPlot)",
                            clearWith=list(
                                "vars",
                                "group",
                                "hwPerm",
                                "hweSplitOutcome",
                                "outcome",
                                "xLinked",
                                "gender",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="barPlot",
                            title="Genotype barplot (Observed vs Expected)",
                            width=650,
                            height=450,
                            renderFun=".plotBar",
                            requiresData=TRUE,
                            visible="(barPlot)",
                            clearWith=list(
                                "vars",
                                "group",
                                "hweSplitOutcome",
                                "outcome",
                                "xLinked",
                                "gender",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    assocTable = function() private$.items[["assocTable"]],
                    assocForest = function() private$.items[["assocForest"]],
                    manhattanPlot = function() private$.items[["manhattanPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assocGroup",
                            title="Phenotype Association Tests")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="assocTable",
                            title="Genetic Association Analysis",
                            visible="(assocEnable)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "geneticModel",
                                "adjust",
                                "covs",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Marker", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="model", 
                                    `title`="Genetic model", 
                                    `type`="text"),
                                list(
                                    `name`="counts_cases", 
                                    `title`="Genotypes Cases", 
                                    `type`="text"),
                                list(
                                    `name`="counts_ctrls", 
                                    `title`="Genotypes Controls", 
                                    `type`="text"),
                                list(
                                    `name`="or_val", 
                                    `title`="Odds Ratio", 
                                    `type`="number"),
                                list(
                                    `name`="or_lower", 
                                    `title`="OR Lower 95% CI", 
                                    `type`="number"),
                                list(
                                    `name`="or_upper", 
                                    `title`="OR Upper 95% CI", 
                                    `type`="number"),
                                list(
                                    `name`="p_val", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="p_adj", 
                                    `title`="p-adjusted", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="assocForest",
                            title="Odds Ratio Forest Plot",
                            width=650,
                            height=500,
                            renderFun=".plotForest",
                            requiresData=TRUE,
                            visible="(assocEnable && assocForest)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "geneticModel",
                                "adjust",
                                "covs",
                                "assocForestTrunc",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="manhattanPlot",
                            title="Pseudo-Manhattan Plot of Association p-values",
                            width=650,
                            height=400,
                            renderFun=".plotManhattan",
                            requiresData=TRUE,
                            visible="(assocEnable && manhattanPlot)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "geneticModel",
                                "covs",
                                "adjust",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    qcTable = function() private$.items[["qcTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="qcGroup",
                            title="Quality Control (QC) Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="qcTable",
                            title="Quality Control Summary",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe",
                                "gender",
                                "xLinked"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Marker", 
                                    `type`="text"),
                                list(
                                    `name`="call_rate", 
                                    `title`="Call Rate", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="maf", 
                                    `title`="MAF", 
                                    `type`="number"),
                                list(
                                    `name`="hwe_p", 
                                    `title`="HWE p-value (Controls)", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="status", 
                                    `title`="Status", 
                                    `type`="text"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    popTable = function() private$.items[["popTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="popGroup",
                            title="Population genetics metrics")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="popTable",
                            title="Marker Informative Metrics",
                            visible="(popMetrics)",
                            clearWith=list(
                                "vars",
                                "mafThreshold",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe",
                                "gender",
                                "xLinked"),
                            columns=list(
                                list(
                                    `name`="marker", 
                                    `title`="Marker", 
                                    `type`="text"),
                                list(
                                    `name`="maf", 
                                    `title`="MAF", 
                                    `type`="number"),
                                list(
                                    `name`="pic", 
                                    `title`="PIC", 
                                    `type`="number"),
                                list(
                                    `name`="shannon", 
                                    `title`="Shannon Index (I)", 
                                    `type`="number"),
                                list(
                                    `name`="ne", 
                                    `title`="Effective Alleles (Ne)", 
                                    `type`="number"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    mdrBestTable = function() private$.items[["mdrBestTable"]],
                    mdrCellTable = function() private$.items[["mdrCellTable"]],
                    mdrHeatmap = function() private$.items[["mdrHeatmap"]],
                    mdrBarPlot = function() private$.items[["mdrBarPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="mdrGroup",
                            title="Multifactor Dimensionality Reduction (MDR)")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="mdrBestTable",
                            title="Best MDR Models by Order",
                            visible="(mdrEnable)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "mdrOrder",
                                "mdrFolds",
                                "mdrPermTest",
                                "nPermMDR",
                                "mdrSeed",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="order", 
                                    `title`="Order", 
                                    `type`="integer"),
                                list(
                                    `name`="combination", 
                                    `title`="Best Combination", 
                                    `type`="text"),
                                list(
                                    `name`="train_ba", 
                                    `title`="Training BA", 
                                    `type`="number"),
                                list(
                                    `name`="test_ba", 
                                    `title`="Testing BA", 
                                    `type`="number"),
                                list(
                                    `name`="cvc", 
                                    `title`="CVC", 
                                    `type`="integer"),
                                list(
                                    `name`="p_val", 
                                    `title`="Permutation p", 
                                    `type`="number", 
                                    `format`="zto,pvalue", 
                                    `visible`="(mdrPermTest)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="mdrCellTable",
                            title="Detailed Cell Risk Classification",
                            visible="(mdrEnable && mdrCellTable)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "mdrOrder",
                                "mdrFolds",
                                "mdrSeed",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="combination", 
                                    `title`="Best Combination", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="cell", 
                                    `title`="Genotypes", 
                                    `type`="text"),
                                list(
                                    `name`="cases", 
                                    `title`="Cases", 
                                    `type`="integer"),
                                list(
                                    `name`="controls", 
                                    `title`="Controls", 
                                    `type`="integer"),
                                list(
                                    `name`="ratio", 
                                    `title`="Cases/Controls Ratio", 
                                    `type`="number"),
                                list(
                                    `name`="risk", 
                                    `title`="Risk Classification", 
                                    `type`="text"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="mdrHeatmap",
                            title="MDR Interaction Heatmap",
                            width=400,
                            height=340,
                            renderFun=".plotMDRHeatmap",
                            requiresData=TRUE,
                            visible="(mdrEnable && mdrHeatmap)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "mdrOrder",
                                "mdrFolds",
                                "mdrSeed",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="mdrBarPlot",
                            title="MDR Model Performance Comparison",
                            width=400,
                            height=500,
                            renderFun=".plotMDRBar",
                            requiresData=TRUE,
                            visible="(mdrEnable && mdrBarPlot)",
                            clearWith=list(
                                "vars",
                                "outcome",
                                "mdrOrder",
                                "mdrFolds",
                                "mdrSeed",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ldTable = function() private$.items[["ldTable"]],
                    ldHeatmap = function() private$.items[["ldHeatmap"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ldGroup",
                            title="Linkage Disequilibrium (LD) Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ldTable",
                            title="Linkage Disequilibrium (LD) Table",
                            visible="(ldEnable && ldTable)",
                            clearWith=list(
                                "vars",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe"),
                            columns=list(
                                list(
                                    `name`="marker1", 
                                    `title`="Marker 1", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="marker2", 
                                    `title`="Marker 2", 
                                    `type`="text"),
                                list(
                                    `name`="d", 
                                    `title`="D", 
                                    `type`="number"),
                                list(
                                    `name`="d_prime", 
                                    `title`="D'", 
                                    `type`="number"),
                                list(
                                    `name`="r2", 
                                    `title`="r\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="p_val", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ldHeatmap",
                            title="LD Heatmap",
                            width=600,
                            height=550,
                            renderFun=".plotLDHeatmap",
                            requiresData=TRUE,
                            visible="(ldEnable && ldHeatmap)",
                            clearWith=list(
                                "vars",
                                "ldMetric",
                                "qcCallRate",
                                "qcMaf",
                                "qcHwe")))}))$new(options=options))
            self$add(jmvcore::Output$new(
                options=options,
                name="prsOutput",
                title="Polygenic Risk Score"))}))

mSNPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mSNPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mSNP",
                version = c(1,0,0),
                options = options,
                results = mSNPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Single Nucleotide Polymorphism
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param outcome .
#' @param covs .
#' @param freqTable .
#' @param freqPct .
#' @param groupTable .
#' @param groupAlleles .
#' @param polyDf1 .
#' @param groupTotal .
#' @param hwTests .
#' @param alpha .
#' @param hwPerm .
#' @param nPerm .
#' @param ternaryPlot .
#' @param ternaryRegion .
#' @param ternaryShowMAF .
#' @param qqPlot .
#' @param barPlot .
#' @param hweSplitOutcome .
#' @param gender .
#' @param xLinked .
#' @param assocEnable .
#' @param geneticModel .
#' @param assocForest .
#' @param assocForestTrunc .
#' @param manhattanPlot .
#' @param popMetrics .
#' @param mafThreshold .
#' @param mdrEnable .
#' @param mdrOrder .
#' @param mdrFolds .
#' @param mdrPermTest .
#' @param nPermMDR .
#' @param mdrSeed .
#' @param mdrCellTable .
#' @param mdrHeatmap .
#' @param mdrBarPlot .
#' @param ldEnable .
#' @param ldTable .
#' @param ldHeatmap .
#' @param ldMetric .
#' @param adjust .
#' @param qcCallRate .
#' @param qcMaf .
#' @param qcHwe .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$hweGroup$freqTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hweGroup$groupAnalysisTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hweGroup$hwTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hweGroup$ternaryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$hweGroup$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$hweGroup$barPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$assocGroup$assocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$assocGroup$assocForest} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$assocGroup$manhattanPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qcGroup$qcTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$popGroup$popTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mdrGroup$mdrBestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mdrGroup$mdrCellTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mdrGroup$mdrHeatmap} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mdrGroup$mdrBarPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ldGroup$ldTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ldGroup$ldHeatmap} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$prsOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
mSNP <- function(
    data,
    vars,
    group,
    outcome,
    covs,
    freqTable = TRUE,
    freqPct = FALSE,
    groupTable = TRUE,
    groupAlleles = TRUE,
    polyDf1 = FALSE,
    groupTotal = FALSE,
    hwTests = TRUE,
    alpha = "0.05",
    hwPerm = FALSE,
    nPerm = 1000,
    ternaryPlot = FALSE,
    ternaryRegion = "1",
    ternaryShowMAF = FALSE,
    qqPlot = FALSE,
    barPlot = FALSE,
    hweSplitOutcome = FALSE,
    gender,
    xLinked = FALSE,
    assocEnable = FALSE,
    geneticModel = "all",
    assocForest = FALSE,
    assocForestTrunc = TRUE,
    manhattanPlot = FALSE,
    popMetrics = FALSE,
    mafThreshold = "none",
    mdrEnable = FALSE,
    mdrOrder = "2",
    mdrFolds = "10",
    mdrPermTest = FALSE,
    nPermMDR = 100,
    mdrSeed = 42,
    mdrCellTable = FALSE,
    mdrHeatmap = FALSE,
    mdrBarPlot = FALSE,
    ldEnable = FALSE,
    ldTable = TRUE,
    ldHeatmap = FALSE,
    ldMetric = "r2",
    adjust = "none",
    qcCallRate = "none",
    qcMaf = "none",
    qcHwe = "none") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mSNP requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(gender)) gender <- jmvcore::resolveQuo(jmvcore::enquo(gender))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(gender), gender, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in gender) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mSNPOptions$new(
        vars = vars,
        group = group,
        outcome = outcome,
        covs = covs,
        freqTable = freqTable,
        freqPct = freqPct,
        groupTable = groupTable,
        groupAlleles = groupAlleles,
        polyDf1 = polyDf1,
        groupTotal = groupTotal,
        hwTests = hwTests,
        alpha = alpha,
        hwPerm = hwPerm,
        nPerm = nPerm,
        ternaryPlot = ternaryPlot,
        ternaryRegion = ternaryRegion,
        ternaryShowMAF = ternaryShowMAF,
        qqPlot = qqPlot,
        barPlot = barPlot,
        hweSplitOutcome = hweSplitOutcome,
        gender = gender,
        xLinked = xLinked,
        assocEnable = assocEnable,
        geneticModel = geneticModel,
        assocForest = assocForest,
        assocForestTrunc = assocForestTrunc,
        manhattanPlot = manhattanPlot,
        popMetrics = popMetrics,
        mafThreshold = mafThreshold,
        mdrEnable = mdrEnable,
        mdrOrder = mdrOrder,
        mdrFolds = mdrFolds,
        mdrPermTest = mdrPermTest,
        nPermMDR = nPermMDR,
        mdrSeed = mdrSeed,
        mdrCellTable = mdrCellTable,
        mdrHeatmap = mdrHeatmap,
        mdrBarPlot = mdrBarPlot,
        ldEnable = ldEnable,
        ldTable = ldTable,
        ldHeatmap = ldHeatmap,
        ldMetric = ldMetric,
        adjust = adjust,
        qcCallRate = qcCallRate,
        qcMaf = qcMaf,
        qcHwe = qcHwe)

    analysis <- mSNPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

