
# This file is automatically generated, you probably don't want to edit this

mUIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mUIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            test = NULL,
            ref = NULL,
            refval = NULL,
            isMCI = FALSE,
            isProp = FALSE,
            UImethod = "TGR",
            minSe = 90,
            minSp = 90,
            uiSe = 55,
            uiSp = 55,
            isROC = FALSE,
            isTGR = TRUE,
            isMD = TRUE,
            youden = FALSE,
            polygon = TRUE,
            model = "none", ...) {

            super$initialize(
                package="jYS",
                name="mUI",
                requiresData=TRUE,
                ...)

            private$..test <- jmvcore::OptionVariables$new(
                "test",
                test,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ref <- jmvcore::OptionVariable$new(
                "ref",
                ref,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..refval <- jmvcore::OptionLevel$new(
                "refval",
                refval,
                variable="(ref)")
            private$..isMCI <- jmvcore::OptionBool$new(
                "isMCI",
                isMCI,
                default=FALSE)
            private$..isProp <- jmvcore::OptionBool$new(
                "isProp",
                isProp,
                default=FALSE)
            private$..UImethod <- jmvcore::OptionList$new(
                "UImethod",
                UImethod,
                options=list(
                    "TGR",
                    "UI",
                    "noUI"),
                default="TGR")
            private$..minSe <- jmvcore::OptionNumber$new(
                "minSe",
                minSe,
                min=75,
                max=99,
                default=90)
            private$..minSp <- jmvcore::OptionNumber$new(
                "minSp",
                minSp,
                min=75,
                max=99,
                default=90)
            private$..uiSe <- jmvcore::OptionNumber$new(
                "uiSe",
                uiSe,
                min=51,
                max=80,
                default=55)
            private$..uiSp <- jmvcore::OptionNumber$new(
                "uiSp",
                uiSp,
                min=51,
                max=80,
                default=55)
            private$..isROC <- jmvcore::OptionBool$new(
                "isROC",
                isROC,
                default=FALSE)
            private$..isTGR <- jmvcore::OptionBool$new(
                "isTGR",
                isTGR,
                default=TRUE)
            private$..isMD <- jmvcore::OptionBool$new(
                "isMD",
                isMD,
                default=TRUE)
            private$..youden <- jmvcore::OptionBool$new(
                "youden",
                youden,
                default=FALSE)
            private$..polygon <- jmvcore::OptionBool$new(
                "polygon",
                polygon,
                default=TRUE)
            private$..decision <- jmvcore::OptionOutput$new(
                "decision")
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "none",
                    "binormal"),
                default="none")

            self$.addOption(private$..test)
            self$.addOption(private$..ref)
            self$.addOption(private$..refval)
            self$.addOption(private$..isMCI)
            self$.addOption(private$..isProp)
            self$.addOption(private$..UImethod)
            self$.addOption(private$..minSe)
            self$.addOption(private$..minSp)
            self$.addOption(private$..uiSe)
            self$.addOption(private$..uiSp)
            self$.addOption(private$..isROC)
            self$.addOption(private$..isTGR)
            self$.addOption(private$..isMD)
            self$.addOption(private$..youden)
            self$.addOption(private$..polygon)
            self$.addOption(private$..decision)
            self$.addOption(private$..model)
        }),
    active = list(
        test = function() private$..test$value,
        ref = function() private$..ref$value,
        refval = function() private$..refval$value,
        isMCI = function() private$..isMCI$value,
        isProp = function() private$..isProp$value,
        UImethod = function() private$..UImethod$value,
        minSe = function() private$..minSe$value,
        minSp = function() private$..minSp$value,
        uiSe = function() private$..uiSe$value,
        uiSp = function() private$..uiSp$value,
        isROC = function() private$..isROC$value,
        isTGR = function() private$..isTGR$value,
        isMD = function() private$..isMD$value,
        youden = function() private$..youden$value,
        polygon = function() private$..polygon$value,
        decision = function() private$..decision$value,
        model = function() private$..model$value),
    private = list(
        ..test = NA,
        ..ref = NA,
        ..refval = NA,
        ..isMCI = NA,
        ..isProp = NA,
        ..UImethod = NA,
        ..minSe = NA,
        ..minSp = NA,
        ..uiSe = NA,
        ..uiSp = NA,
        ..isROC = NA,
        ..isTGR = NA,
        ..isMD = NA,
        ..youden = NA,
        ..polygon = NA,
        ..decision = NA,
        ..model = NA)
)

mUIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mUIResults",
    inherit = jmvcore::Group,
    active = list(
        stat = function() private$.items[["stat"]],
        plotsTGR = function() private$.items[["plotsTGR"]],
        plotsMD = function() private$.items[["plotsMD"]],
        plotsROC = function() private$.items[["plotsROC"]],
        decision = function() private$.items[["decision"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Uncertain Interval (UI)",
                refs=list(
                    "jys",
                    "uir",
                    "lsh",
                    "lshd"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    uistat = function() private$.items[["uistat"]],
                    mcistat = function() private$.items[["mcistat"]],
                    intstat = function() private$.items[["intstat"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="stat",
                            title="Intervals Estimation")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="uistat",
                            title="Uncertain Interval (UI)",
                            clearWith=list(
                                "ref",
                                "test"),
                            rows="(test)",
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="Predictor", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="dir", 
                                    `title`="Direction", 
                                    `type`="text"),
                                list(
                                    `name`="int", 
                                    `title`="Intersection", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="mcistat",
                            title="More Certain Interval (MCI)",
                            clearWith=list(
                                "ref",
                                "test"),
                            rows="(test)",
                            visible="(isMCI)",
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="Predictor", 
                                    `type`="text", 
                                    `content`="($key)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="intstat",
                            title="Proportions of Intervals",
                            clearWith=list(
                                "ref",
                                "test"),
                            visible="(isProp)",
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="Predictor", 
                                    `type`="text"),
                                list(
                                    `name`="lev", 
                                    `title`="Level", 
                                    `type`="text"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="plotsTGR",
                title="Two-graph ROC curves",
                visible="(isTGR)",
                items="(test)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plotTGR",
                    requiresData=TRUE)))
            self$add(jmvcore::Array$new(
                options=options,
                name="plotsMD",
                title="Mixed Densities",
                visible="(isMD)",
                items="(test)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plotMD",
                    requiresData=TRUE)))
            self$add(jmvcore::Array$new(
                options=options,
                name="plotsROC",
                title="ROC curves",
                visible="(isROC)",
                items="(test)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=500,
                    renderFun=".plotROC",
                    requiresData=TRUE)))
            self$add(jmvcore::Output$new(
                options=options,
                name="decision",
                title="Proposed decision"))}))

mUIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mUIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mUI",
                version = c(1,0,11),
                options = options,
                results = mUIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Uncertain Interval (UI)
#'
#' 
#' @param data .
#' @param test .
#' @param ref .
#' @param refval .
#' @param isMCI .
#' @param isProp .
#' @param UImethod .
#' @param minSe .
#' @param minSp .
#' @param uiSe .
#' @param uiSp .
#' @param isROC .
#' @param isTGR .
#' @param isMD .
#' @param youden .
#' @param polygon .
#' @param model .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$stat$uistat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stat$mcistat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stat$intstat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotsTGR} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$plotsMD} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$plotsROC} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$decision} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
mUI <- function(
    data,
    test,
    ref,
    refval,
    isMCI = FALSE,
    isProp = FALSE,
    UImethod = "TGR",
    minSe = 90,
    minSp = 90,
    uiSe = 55,
    uiSp = 55,
    isROC = FALSE,
    isTGR = TRUE,
    isMD = TRUE,
    youden = FALSE,
    polygon = TRUE,
    model = "none") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mUI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(test)) test <- jmvcore::resolveQuo(jmvcore::enquo(test))
    if ( ! missing(ref)) ref <- jmvcore::resolveQuo(jmvcore::enquo(ref))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(test), test, NULL),
            `if`( ! missing(ref), ref, NULL))

    for (v in ref) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mUIOptions$new(
        test = test,
        ref = ref,
        refval = refval,
        isMCI = isMCI,
        isProp = isProp,
        UImethod = UImethod,
        minSe = minSe,
        minSp = minSp,
        uiSe = uiSe,
        uiSp = uiSp,
        isROC = isROC,
        isTGR = isTGR,
        isMD = isMD,
        youden = youden,
        polygon = polygon,
        model = model)

    analysis <- mUIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

