
# This file is automatically generated, you probably don't want to edit this

mXLSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mXLSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            xlsexport = NULL, ...) {

            super$initialize(
                package="jYS",
                name="mXLS",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..xlsexport <- jmvcore::OptionAction$new(
                "xlsexport",
                xlsexport)

            self$.addOption(private$..vars)
            self$.addOption(private$..xlsexport)
        }),
    active = list(
        vars = function() private$..vars$value,
        xlsexport = function() private$..xlsexport$value),
    private = list(
        ..vars = NA,
        ..xlsexport = NA)
)

mXLSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mXLSResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Export Data to Excel")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Export Data to Excel"))}))

mXLSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mXLSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jYS",
                name = "mXLS",
                version = c(1,0,0),
                options = options,
                results = mXLSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Export Data to Excel
#'
#' 
#' @param data .
#' @param vars .
#' @param xlsexport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
mXLS <- function(
    data,
    vars,
    xlsexport) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mXLS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- mXLSOptions$new(
        vars = vars,
        xlsexport = xlsexport)

    analysis <- mXLSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

